### ISSUE TITLE
When I "enableDebug" for ASP.Net MVC5 app, I get a javascript assert - client performance math error: 831

### ISSUE THREAD

**Issue by petehauge** [Microsoft/ApplicationInsights-JS#1]
I followed the steps here:
http://azure.microsoft.com/en-us/documentation/articles/app-insights-api-custom-events-metrics/#track-event to enable app insights for my ASP.Net MVC5 app.  Everything works except when I try to enable developer mode with this code:
// Insert this in the initialization script, just before trackPageView:
appInsights.config.enableDebug = true;

When I add that line of code and hit F5 (start debugging) in Visual studio, I hit the attached exception.
![javascript](https://cloud.githubusercontent.com/assets/12090616/7307825/42eae210-e9dd-11e4-9edb-9f597e3112b5.png)

**Comment by MaxShehovtsov** [comment]
We use window.performance.timing to get page performance info (see https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/JavaScriptSDK/Telemetry/PageViewPerformance.ts). When total is less than parts that should sum it up we log an error - this is something that can be investigated further (do we use performance timing api incorrectly?). This issue appears from time to time on different environments but we never got a chance to investigate it yet. 
Having said that, In developer mode it's expected that you see the popup window with an error. If you just want to swallow it (because it's not user actionable) you could just turn developer mode off (set enableDebug=false)

**Comment by SergKanz** [comment]
@alancameronwills we need to update documentation - for javascript we do not need to set debugMode - it is only for diagnostics

**Comment by MaxShehovtsov** [comment]
debugMode was removed
