### ISSUE TITLE
Update to TypeScript 4.x

### ISSUE THREAD

**Issue by aaronpowell** [microsoft/ApplicationInsights-JS#1071]
The project uses TypeScript version 2.5.3 while the current latest version is 3.6.3 (with 3.7 beta just becoming available).

While there's a number of updates to the language that may be beneficial there's also updates to the core definitions. One definition update in particular would be useful to address the definition patching required for #1070.

**Comment by MSNev** [comment]
Because of the length of time this has been taking, I'm changing this to jump to TypeScript v4.x -- hopefully we can complete this before TS 5 comes out 😅

**Comment by aaronpowell** [comment]
Any help you need @MSNev?

**Comment by MSNev** [comment]
I don't think so, it's mostly a matter of timing and juggling with internal teams, tasks and compatibility issues. As there has been issues with the generated code (previously) especially the *.d.ts, I've since tasks for the apigenerator to mitigate this aspect and make it easier to identify and validate any possible breaks.

**Comment by MSNev** [comment]
v2.7.0 is not fully deployed to NPM and all CDN endpoints -- 🎆 🥳 🍾
