### ISSUE TITLE
Correlation ID Not Being Sent To App Insights

### ISSUE THREAD

**Issue by mindingdata** [microsoft/ApplicationInsights-JS#1119]
I am attempting to correlate my API backend with my front end in App Insights but I'm running into a similar issue as : https://github.com/microsoft/ApplicationInsights-JS/issues/1019 whereby the request context is passed back and forth correctly from Front End to API and back again, but when the call goes to Application Insights it doesn't pass the CID. 

I am testing this all locally with an Angular App running at localhost:4200 and a .NET Core API running at localhost:5000. In my live environment, they are on separate domains so I am running CORS. 

When I make an example request to say login, I can see that the front end is sending Request-Context, Request-id and traceparent all correctly. I can also see the API responding with the correct Request-Context : 

![image](https://user-images.githubusercontent.com/1021021/69109254-0ddea780-0adc-11ea-84f3-25b3eefc04b9.png)

However when the next call to "track" comes in, it does not include the CID : 

![image](https://user-images.githubusercontent.com/1021021/69109288-277fef00-0adc-11ea-9c0c-1f51be96a106.png)

SDK Version : 2.3.1

I am creating the App Insights object in an Angular App like so : 
```
new ApplicationInsights({
      config: {
        instrumentationKey: appConfigService.instrumentationKey, 
        disableCorrelationHeaders : false, 
        enableCorsCorrelation : true,
        distributedTracingMode : DistributedTracingModes.AI_AND_W3C
      }
    }
```

**Comment by markwolff** [comment]
I finally had a chance to look at this. It is probably because your backend does not set the [`Access-Control-Expose-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) header. In one of my (express) demos I only needed to add `    res.header('Access-Control-Expose-Headers', 'request-context'); See this [StackOverflow](https://stackoverflow.com/questions/8945587/xmlhttprequest-getallresponseheaders-not-returning-all-the-headers) for more info.
`
