### ISSUE TITLE
[BUG] trackEvent is logging some properties to measurements column

### ISSUE THREAD

**Issue by 3xj** [microsoft/ApplicationInsights-JS#1166]
It looks like, starting with v2, custom event properties sent using `trackEvent()` are split into two different columns: `customDimensions` for non-numeric values, and `customMeasurements` for numeric ones. E.g.
`trackEvent(
    { name: "myCustomEvent" },
    {
        type: "user",
        id: 1234
    }
);`

results in the following pulled from log analytics:
```
| name          | customDimensions   | customMeasurements |
----------------------------------------------------------
| myCustomEvent | { "type": "user" } | { "id": 1234 }     |
----------------------------------------------------------
```

Is this expected behavior? Previously, everything in the "properties" bucket would go into `customDimensions`; there was a separate argument in the method contract for putting items into `customMeasurements`.

Version `2.3.1`

**Comment by xiao-lix** [comment]
@3xj Yes it is expected behavior. When the telemetry event is created [here](https://github.com/microsoft/ApplicationInsights-JS/blob/7a800f19805716b137670299183cd4adbb8348ac/shared/AppInsightsCommon/src/TelemetryItemCreator.ts#L48), customProperties are put into `data` field. And before the event is sent out, data field is parsed again and put number values data into `measurement` field, other types data into `properties` field, reference [here](https://github.com/microsoft/ApplicationInsights-JS/blob/7a800f19805716b137670299183cd4adbb8348ac/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts#L26). However, [`measurement`](https://github.com/microsoft/ApplicationInsights-JS/blob/7a800f19805716b137670299183cd4adbb8348ac/shared/AppInsightsCommon/src/Interfaces/IPartC.ts#L15) field is deprecated, `properties` field can accept any type. Please update to track event with instruction [here](https://github.com/microsoft/ApplicationInsights-JS#sending-telemetry-to-the-azure-portal). Your example would be: 
```
trackEvent({
    name: 'myCustomEvent',
    properties: {
        type: 'user',
        id: 1234
    }
})
```
