### ISSUE TITLE
ICustomProperties vs IPartC.properties

### ISSUE THREAD

**Issue by mpaul31** [microsoft/ApplicationInsights-JS#1222]
Hello,

I noticed many of the trackXXX methods accept a type that extends IPartC (ITraceTelemetry) as well as a second parameter of type `ICustomProperties`. When would you choose one over the other. It appears both just write custom dimensions.

Thanks

**Comment by MSNev** [comment]
Hi,

It really depends on your use case, on whether you pass the values in the properties value of the IPartC event or in the ICustomProperties. For example, perhaps you have values you want some consistent values added to every event but you create events from multiple locations in your code. In this case in might be easier to just create and reuse the custom properties passed to every track event rather than constructing and adding these properties on event event.

Note: that values in the customProperties will REPLACE any values in the properties with the same name.

`                    let props = {
                        propA: "a"
                    };
                    let customProps = { 
                        customA: "customA"
                    }
                    appInsights.trackEvent({ name:"customPropTest", properties: props }, customProps);
`
In the following case the customDimension of propA will be sent as "cpa" and not "a"
`
                    let props = {
                        propA: "a"
                    };
                    let customProps = { 
                        customA: "customA",
                        propA: "cpa"
                    }
                   appInsights.trackEvent({ name:"customPropTest", properties: props }, customProps);
`

**Comment by mpaul31** [comment]
awesome thanks!
