### ISSUE TITLE
Upgrading the tslib dependency to 1.11.1

### ISSUE THREAD

**Issue by asankaf** [microsoft/ApplicationInsights-JS#1242]
**Description**
The latest version of @microsoft/applicationinsights-web 2.5.3 still uses tslib 1.10.0. Our application uses a relatively new version of typescript which requires us to have tslib 1.11.0. But with the duplicate dependency, we have to add aliases in our webpack.config to get around the problem. I believe it's high time to upgrade the tslib from 1.10.0 to latest (1.11.1)

**Steps to Reproduce**

 - OS/Browser: Windows / Chrome (Version 80.0.3987.149)
 - SDK Version [e.g. 22]: 2.5.3
 - How you initialized the SDK: NPM setup / webpack

**Expected behavior**
Next version to be released with tslib 1.11.1

**Comment by josundt** [comment]
`tslib` **1.11.1** does not contain any breaking changes and should be backwards compatible as far a I know. 

Latest version of `tslib` (currently 1.11.1) it is required for code compiled with the latest versions of TypeScript (when compiled with `--importHelpers=true`), since some new TypeScript features depend on importHelper support functions in latest version of tslib for downlevel transpilation. 

The problem with the @microsoft/applicationinsights-__x__ npm packages is that they have an **exact** version dependency to `tslib` **1.10.0**. It should not cause any harm to have a less strict version requirement.

It should at least be changed to **^1.10.0** (notice the caret that ensures minor version tolerance) to avoid conflicts/duplicate version dependencies when used in combination with other packages that are built with some of the **_latest_** versions of TypeScript.

**Comment by MSNev** [comment]
We originally had ^1.x.x, however, when 1.11.0 was released it contained breaking changes that broke us, so we had to shift to the last known working version which was 1.10.0 (#1199 - Feb 25th). I raised a issue on tslib which they have since fixed and released as 1.11.1 but I've not yet had cycles to move forward again... I've use this Issue as the work item, but it may not be the next release.

**Comment by jfmartinez83** [comment]
Hi there,

when this new version is going to released ? this is causing issues in our pipelines.

thanks

**Comment by MSNev** [comment]
Fixed deployed as NPM and next CDN channels

**Comment by MSNev** [comment]
Closing as this is an NPM issue only
