### ISSUE TITLE
[DOCS] How to get ai session id for debug purposes

### ISSUE THREAD

**Issue by jean-moldovan** [microsoft/ApplicationInsights-JS#1256]
Hello!

I'd love to spit out ai session id to the console for debug / investigation purposes. Currently it is not clear where to get it from.

I'm on a SPA app and this is how I initialize app insights:
```
  const appInsights = new ApplicationInsights({
    config: {
      instrumentationKey: 'xxxx'
    }
  })

  appInsights.loadAppInsights()
```

Then I'd track the page on route change:
```
  router.beforeEach((to, from, next) => {
    appInsights.startTrackPage(to.fullPath)
    next()
  })

  router.afterEach((to, from) => {
    appInsights.stopTrackPage(from.fullPath)
  })
```

1) How can I access ai session id from my js code?
2) If I track the page manually on route change do I still need to initialize the session by calling `trackPageView ` on app insights load?
```
appInsights.loadAppInsights();
appInsights.trackPageView();
```

Thanks!

**Comment by MSNev** [comment]
Not sure I'm going to completly answer your question here but..

For  if you want to link your initial server request to the page request you would need to do something like the following after you have initialized the sdk and before the first track call (i.e. the page view -- otherwise that won't be linked correctly)

if (aisdk.queue && aisdk.queue.length === 0) {
    aisdk.properties.context.telemetryTrace.traceID = "<server operation id>"
    aisdk.properties.context.telemetryTrace.parentID = "<server request id>"
    aisdk.properties.context.telemetryTrace.name = "<server operation name>"
}

If you don't want to link you server and client requests together then you can also reference the above values (aisdk.properties.context.telemetryTrace.xxxx) to get the values. The trace id I don't believe is set until after the first request (event) is sent.

**Comment by jean-moldovan** [comment]
Found an answer in https://github.com/microsoft/ApplicationInsights-JS/issues/943.
Closing.
