### ISSUE TITLE
[BUG] @microsoft/applicationinsights-web fails to initialize with latest version

### ISSUE THREAD

**Issue by jepetty** [microsoft/ApplicationInsights-JS#1321]
**Description/Screenshot**
Starting this morning, our application insights instance began failing to initialize:
> TypeError: Cannot set property 'snippetVer' of undefined
	at _updateSnippetProperties (Initialization.js?e727:236)
	at Initialization.loadAppInsights (Initialization.js?e727:263)
	at new OnlineTelemetryClient (OnlineTelemetryClient.ts?ed0c:20)
	at Object.eval (Telemetry.ts?e430:72)
	at Generator.next (<anonymous>)
	at eval (Telemetry.ts?e430:5)
	at new Promise (<anonymous>)
	at __awaiter (Telemetry.ts?e430:5)
	at Object.initializeTelemetry (Telemetry.ts?e430:62)
	at eval (Extension.ts?7991:33)
	at Generator.next (<anonymous>)
	at eval (Extension.ts?7991:5)
	at new Promise (<anonymous>)
	at __awaiter (Extension.ts?7991:5)
	at activate (Extension.ts?7991:31)
	at Function._callActivateOptional (extHostExtensionService.ts:418)
	at Function._callActivate (extHostExtensionService.ts:407)
	at extHostExtensionService.ts:362

**Steps to Reproduce**
Initialize a new instance of Application Insights with a non-null snippet. Our snippet:
```ts
this.appInsights = new ApplicationInsights({
			config: {
				instrumentationKey,
				endpointUrl: 'https://vortex.data.microsoft.com/collect/v1',
				emitLineDelimitedJson: true,
				isCookieUseDisabled: true,
			},
		});
```

 - OS/Browser:
Windows - Chrome and Edge

 - SDK Version [e.g. 22]:
Using version 2.5.6 of the @microsoft/applicationinsights-web NPM package
**NOTE:** this works in version 2.5.3 (and I presume lower)

**Comment by MSNev** [comment]
Hi @jepetty, 

This looks like where the issue is occurring
https://github.com/microsoft/ApplicationInsights-JS/blob/master/AISKU/src/Initialization.ts#L284

And looking at the code this looks like it an issue when running in an environment that doesn't support a window, as the internal property of the context object won't get populated.
https://github.com/microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-properties-js/src/TelemetryContext.ts#L37

So when you say "Starting this morning, our application insights instance began failing to initialize:" what has changed?
Is this an upgrade from 2.5.3 to 2.5.6? 
Or was this previously working for 2.5.6?

Cheers

Nev

**Comment by SachiraChin** [comment]
@MSNev I've got the same issue while working on `gatsby` site. I actually thought it was an issue with my environment first. I will add details of the error(s) I got here in case someone else gets this.

## Error symptoms

When you use `ApplicationInsights` in site without using [`NPM Setup`](https://github.com/microsoft/applicationinsights-js#npm-setup-ignore-if-using-snippet-setup), you may have got errors like this. 

- `ReferenceError: XMLHttpRequest is not defined`
- `ReferenceError: XDomainRequest is not defined`
- `TypeError: Cannot set property 'snippetVer' of undefined`

For me, I got each error in order mentioned above after trying to fixing each, for example, to fix `ReferenceError: XMLHttpRequest is not defined`, I tried,

```bash
npm install xhr2 --save
```
```js
if (!("XMLHttpRequest" in global)) {
    global.XMLHttpRequest = require('xhr2');
}
```

After this, I got `ReferenceError: XDomainRequest is not defined`, which I didn't found anyway to import/polyfil, I tried this,

```js
if (!("XMLHttpRequest" in global)) {
    global.XMLHttpRequest = require('xhr2');
    global.XDomainRequest = undefined;
}
```

After above change, I got `TypeError: Cannot set property 'snippetVer' of undefined`, which I didn't know how to fix, and then came across this post.

## Solution

`ApplicationInsights` version I've been using was, `2.5.6`, which seems to be causing the issue. I downgraded it to `2.5.3` by taking clue from @MSNev which solved the issue.

Please note that you still have to use this block if you are getting first two errors.

```bash
npm install xhr2 --save
```
```js
if (!("XMLHttpRequest" in global)) {
    global.XMLHttpRequest = require('xhr2');
    global.XDomainRequest = undefined;
}
```

Hope this helps someone.

**Comment by MSNev** [comment]
The reference errors are interesting, does your gatsby environment not provide any XHR support (which is why you are dragging in a polyfil?).

I'll see if I can address the failures as we want to ensure we work in environments without crashing like this -- do you happen to have the stack trace at all to confirm the location were this is occurring... I have an idea where but I don't want to apply any fix the wrong location(s)

**Comment by MSNev** [comment]
I've also opened a new bug to address the Reference is not defined issues
https://github.com/microsoft/ApplicationInsights-JS/issues/1334

**Comment by SachiraChin** [comment]
@MSNev I'm very new to Gatsby, I'm not very sure if I have done something wrong when I setup my environment. I will add details about how I setup my environment in the ticket you mentioned above for you to reproduce it.

**Comment by MSNev** [comment]
Fully Deployed to CDN and NPM as version 2.5.7
