### ISSUE TITLE
How to pass `applicationVersion` in snippet setup?

### ISSUE THREAD

**Issue by dimaqq** [microsoft/ApplicationInsights-JS#1332]
#31 contains code that shows how to set up `applicationVersion` when instantiating appInsights manually.

How about snippet setup, how can I pass `applicationVersion` then?

P.S. I've tried a few hacks, but it seems that the `context` / `application.ver` is initialised deep in the library...

**Comment by dimaqq** [comment]
For the time being I've used a hack from #371 though I wish there was an easier way.

**Comment by MSNev** [comment]
The approach in #371 is the correct way, after the snippet script you can add

<script type="text/javascript">
<<< Snippet body removed>>> }(window,document,{
src: "https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js", // The SDK URL Source
cfg: { // Application Insights Configuration
    instrumentationKey: "INSTRUMENTATION_KEY"
}});
appInsights.queue.push(function () {
    appInsights.context.application.ver = "myversion";
});
</script>

I have been considering providing an easier way to inject queue items as part of the snippet config, but for now the above would be the approach.

For reference the queue'd function are executed after the appInsights has been loaded and initialized successfully and the appInsights.context object (since 2.5.4 #1232) is now always populated (for a web browser scenario) after initialization.

For a non-web browser based solution the appInsights.context.application will be always set as part of the next release as the fix for this execution path #132 is waiting for the next release (scheduled for next week)

**Comment by MSNev** [comment]
Created feature request #1403 to address my comment above for injecting items into the queue during initialization
