### ISSUE TITLE
App Insights track calls blocking, long wait times

### ISSUE THREAD

**Issue by attrib75** [microsoft/ApplicationInsights-JS#1372]
**Description/Screenshot**
We're experiencing intermittent huge wait times for App Insights calls and wondering what the issue might be. One example is pasted here. A track call is taking over 700 ms to load. The internet connection is fine and other requests for other endpoints on the web succeed in a much shorter time when this is noticed. In addition, the 'track' calls seem to block all other calls, making the whole app wait until it is done before other calls can continue. This may be due to the Chrome's consecutive Ajax request limit. The issue happens in Chrome and Firefox.

![image](https://user-images.githubusercontent.com/1398909/93250226-1df50100-f758-11ea-951d-e07f28e90f54.png)

**Steps to Reproduce**
 Run the app
 - App Version: Angular 7.2
 - SDK Version: applicationinsights-web 2.2.4
 - OS/Browser:  Chrome 85
 - How you initialized the SDK: Yes

**Expected behavior**
Track calls do not take excessively long, do not block

**Comment by MSNev** [comment]
A complete round trip of 700ms (while not optimal) is not impossible, depending on many many external dependencies and network conditions including SSL handshaking, DNS resolution etc so I'm not going to comment explicitly on why it took this long to send 167 bytes (which is still TCP packet) of content.

But, in terms of blocking, this sounds like the event is being sent as synchronous event as part of the call to track. Are you doing any of the following?
- including the "sync" property on the event as a "truthy" (boolean, !0 etc) value?
- Are you calling flush() or triggerSend() specifying that it should happen synchronously?
- Is this event(s) being sent during full web page navigation event  (the base URL is changing -- causing a new request to the server (or a different domain etc).

These are all expected scenario's where this can occur, for the first 2 -- just tell the flush / triggerSend to send the requests as asynchronously or exclude the "evt.sync" field or set it to false.

In the last case, this is required to ensure that all of the unsent events are flushed and sent to the server -- for modern browsers we do attempt to send via the sendBeacon() API if it's available to avoid the blocking.

Additionally, the current version of App insights is 2.5.8, you may want to look at upgrading -- not that I believe it will specifically changes any of the above.

**Comment by attrib75** [comment]
Thanks, I brought these points to the attention of others on my team.  Hopefully they will be able to comment.  Please note that we were seeing instances of much longer wait times, into the double digit seconds.  I don't have a captured log for that but will work on that.  When we see this, the internet isn't an issue.  Can it be that our Azure App Insights is throttling our requests?  We have a lot of apps pointed to one AI instance.  If so, what can we do do rectify that?  thanks

**Comment by MSNev** [comment]
A fiddler trace would help track down network related issues (it also depends a lot on where the requests are sent from / to -- i.e. which region) -- double digits does sound excessive, but on my previous team I did see this occur from multiple locations around the world (even just loading resources from a CDNs). 

Azure Monitor does have regionalized servers to reduce this type of issues and apps using the same AI key will not cause this sort of problem as we have services @ MS that have extreme usages of single AI keys -- So I don't believe that is an issue.

We would really need a network trace (fiddler is enough) to capture both the network connection, send / receive details and the payload (ensure you have HTTP decrypt enabled) so that the individual request(s) could potentially be identified to determine how they made it into the system (this, however, is not owned by this group maintainers of the JS SDK  -- so we would need to pass it onto a different internal team for them to try and track down)

**Comment by attrib75** [comment]
Thanks again for your help.  I'll work on trying to get a trace.  It is good to know that a single key can be used with multiple apps without a performance hit.
