### ISSUE TITLE
Making the sdk's cookies HttpOnly/Secure  

### ISSUE THREAD

**Issue by MaxShehovtsov** [Microsoft/ApplicationInsights-JS#14]
Investigate if we can make our cookies "ai_user" and "ai_session" httponly/secure.

**Comment by codingoutloud** [comment]
For secure (https) sites this will always pop up on even the most rudimentary vulnerability scan or pen test. Then it will consume human resources deciding whether it is okay, wasting time and adding friction to AI adoption. Seems like the right thing to do from defense-in-depth & least privilege point of view. (Unclear whether marking HttpOnly interfere with AI JavaScript client?)

**Comment by alkampfergit** [comment]
I'd like also a way to disable cookie completely, while retaining all the functionalities of client side SDK that do not require cookies. 
This feature is useful for EU Cookie law, especially because, until the user do not accept cookies, we cannot send any cookie to him and the only solution is to disable tracking scripts completely.
If SDK give us the ability to disable cookie, we can Always send the script without cookie, and then, when the user accepts cookie, we can enable them, to have full tracking capabilities.

**Comment by MaxShehovtsov** [comment]
@codingoutloud 
1) we could make cookies 'secure' but only when https is used by the app (otherwise our session feature - when the server side SDK takes the cookie to report a session id - will be broken). It might be tricky though in case an app uses both http and https (what will happen if httpS://app sets up the cookie to be secure, then users goes to httP://app - cookie is alreay created but can't be sent - as it's secure - should we reset it with JS SDK to non secure? Should be possible but need to try it out to be sure).
2) I don't see how we mark our cookies HttpOnly as they need to be modified by javascript which seem to be impossible by definition of HttpOnly cookie (correct me if I'm wrong - I haven't try it myself so might be missing something)

@alkampfergit 
If you disable cookies on browser level - the SDK will keep working without setting cookie correctly. Does this satisfy EU cookie law? Or do you mean we need to disable only SDK cookies as the fact of accessing cookies without user's agreement violates the law?

Thank you guys for your feedback!

**Comment by alkampfergit** [comment]
@MaxShehovtsov Sadly enough the EU Law is restrictive and there is a lot of confusion about it. The general rule is, you cannot send cookies to users without user's agreement.

To avoid problems, many customers simply use script to completely disable analytics until the user accepts to use cookies. if the user refuse to accepts cookies they have zero analytics because the entrire analytics script is not run.

It would be good to have an option in the SDK that will prevent cookie to be sent to the user. With this option we can rendere in the page the script with cookie disabled and then, if the user  give consensus to cookie, we can render the script with cookie enabled.

**Comment by MaxShehovtsov** [comment]
@alkampfergit makes sense.

**Comment by kamilszostak** [comment]
Refreshing and cleaning up this thread: 
* @alkampfergit  an option to disable cookies was added in #336 and will be released by 1/6/2017. 
* the EU Cookie Law support is tracked in this issue #151. 

We will triage the secure cookies this week, I'll provide an update by 1/6/2017.

**Comment by alkampfergit** [comment]
Thanks!!

**Comment by mamoorkhan** [comment]
so what is the status on this one? I am a bit confused
