### ISSUE TITLE
[BUG] 204 response getting stopped in Application Insights

### ISSUE THREAD

**Issue by sccrgoalie1** [microsoft/ApplicationInsights-JS#1424]
**Description/Screenshot**
We have an Angular 10 Application using [flowjs](https://github.com/flowjs/flow.js/) for uploading of files.  Everything works fine until we enable Application Insights then our GET request from flowjs not longer flows through

**Steps to Reproduce**

1. Enable application insights
```
const appInsights = new ApplicationInsights({ config: {
              instrumentationKey: ''
              /* ...Other Configuration Options... */
          } });
      appInsights.loadAppInsights();
      appInsights.trackPageView();
```
2. Try to upload a file using flowjs
3. Flowjs will issue a GET request to see if the chunk has already been uploaded.  Using the native XMLHttpRequest they attach handlers to load/error.  Neither of these event handlers fire as long as application insights is enabled.  The server is returning a 204 No Content response, but something in Application Insights is preventing it from getting back to these event handlers.  See this [method](https://github.com/flowjs/flow.js/blob/e83d2d9d72d0b4f96f34b508fd7d734f36075be2/src/flow.js#L1325) in flowjs.

If I remove the application insights load from app.component.ts everything will work properly.

 - OS/Browser: Edge/Chrome
 - SDK Version [e.g. 22]: 2.5.9

**Comment by MSNev** [comment]
I'm not seeing anything obvious that would cause issues, App Insights adds a readystatechange event that it listens to and for it's wrapped functions it appears to be catching any internal exceptions (so that any internal exceptions doesn't block followup functions).

Can you install the debug plugin (https://github.com/microsoft/ApplicationInsights-JS/tree/master/extensions/applicationinsights-debugplugin-js) in your debug environment, that way any of App Insights internal errors should get propagated to the debug plugins dashboard so that we can see what is going one.

In terms of the response (status) code, we don't do anything special with a 204, we do attempt to access any of the response headers and status response text but both of these should not block any follow up listeners.

**Comment by MSNev** [comment]
You could also try setting the "disableAjaxTracking" configuration property to see if it is in fact the XHR ajax tracking code that is causing the issue and not something else. (i.e. if works when disabled then is something in that code -- just to help narrow down the root source of the issue).

Additional question, are you using any other library that is freezing or sealing the XMLHttpRequest instance?

**Comment by sccrgoalie1** [comment]
> You could also try setting the "disableAjaxTracking" configuration property to see if it is in fact the XHR ajax tracking code that is causing the issue and not something else. (i.e. if works when disabled then is something in that code -- just to help narrow down the root source of the issue).
> 
> Additional question, are you using any other library that is freezing or sealing the XMLHttpRequest instance?

Hi @MSNev,

I set "disableAjaxTracking" and the request starting working.

I installed the debug plugin but the icon in the bottom right isn't clickable for some reason.

I'm not aware of any other library that would be freezing or sealing the XMLHttpRequest.  The two main libraries used for ajax requests are devextreme and angular.

**Comment by MSNev** [comment]
I've not heard of devextreme before (I'll have a look) but we do work in an angular environment...

Debug Plugin not clickable, that's interesting, sounds like the clicks are getting intercepted or something. We did put in some work to enable keyboard navigation so (in theory) you should be able to tab to it and hit enter to trigger...

Is it possible for you to setup a simple repro / example (or supply the source)? So that we can debug into it to try and identify the root cause. As it will be public, don't include anything you don't want exposed to everyone.

**Comment by sccrgoalie1** [comment]
I'll see what I can get put together.

It appears it's not clickable as it's sitting below the angular material overlay, can I set a z-index?

**Comment by MSNev** [comment]
That makes sense, we are planning on making it configurable / movable etc, just one of the reasons it's still in beta.
