### ISSUE TITLE
Page crash iOS Safari in Private mode: infinite loop SessionStorage read warning

### ISSUE THREAD

**Issue by bgever** [Microsoft/ApplicationInsights-JS#144]
As of a few weeks ago, user reported issue with **iOS Safari in Private mode**. Normal mode works fine.

When loading the page with the AI script, the browser reports eventually in a message bar:
`A problem occured with this webpage so it was reloaded.`
and the page content has only the message:
`A problem repeatedly occurred on "<URL>".`.
    

Reproduced with Browserstack real browser on various devices and on my own iPhone.

The console log has repeatedly this message (up to 6400 times):

`ai.0.js:1 AI (Internal): NONUSRACT_BrowserCannotWriteSessionStorage message:"Browser failed write to session storage. " props:"{exception:[object DOMException]{\code\:22,\name\:\QuotaExceededError\,\message\:\QuotaExceededError: DOM Exception 22\,\line\:1,\column\:16686,\sourceURL\:\https://az416426.vo.msecnd.net/scripts/a/ai.0.js\}}"`

[When Safari is in Private mode it doesn't allow to read session storage.](http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st)

[The AI code has a try/catch around that](https://github.com/Microsoft/ApplicationInsights-JS/blob/31aacddd1cb8852af0bc3b2ddcd3b4ae71f15c94/JavaScript/JavaScriptSDK/Util.ts#L186), but somehow the attempt is repeated.

![ai safari private infinite loop](https://cloud.githubusercontent.com/assets/1618765/13740127/f4f566c4-ea09-11e5-8b3a-3788b5320b31.PNG)

**Comment by tsj0603** [comment]
I also have the issue for my web site.

For Safari in private browsing the browser hands out the window.localStorage objet but throws an exception when using the SetItem member.

The problem is in Util.ts. The _getStorageObject and _getSessionStorageObject functions return the storage object but when the write functions use the storage object it throws an exception causing the write functions to return false. This causes the caller loop.

The _getStorage*Object functions should use a pattern where they validate the storage object by performing a test write operation before handing out the object. This is a common pattern - e.g. see https://mathiasbynens.be/notes/localstorage-pattern.

**Comment by bgever** [comment]
Hope the AI team can review the PR which should fix this issue. I can't run the unit tests locally, the PS script opens an HTML page with empty unit tests. I can test the results via Browserstack.

**Comment by bgever** [comment]
@tsj0603 thanks for explaining that. While you were typing that out, I was making the PR, teamwork! :smile:

**Comment by bgever** [comment]
As confirmed in PR #146, the issue has been fixed and CDN has been updated. Again, thanks a lot for the quick fix, @AlexBulankou. :smile:
