### ISSUE TITLE
[BUG] 2.5.10 is not tracking pageViews

### ISSUE THREAD

**Issue by leniency** [microsoft/ApplicationInsights-JS#1445]
The 2.5.10 Javscript SDK does not automatically track page views, and directly calling `appInsights.trackPageView();` doesn't either.

**Steps to Reproduce**

Create a new page and copy/paste the [snippet](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript#snippet-based-setup) into the page `<head>`

Change the `src` option to directly reference the 2.5.10 version:
`src: "https://az416426.vo.msecnd.net/scripts/b/ai.2.5.10.min.js", // The SDK URL Source`

Load the page and it never sends a tracking request.

 - OS/Browser: Edge, Chrome, Firefox (lastest versions each)
 - SDK Version: 2.5.10
 - How you initialized the SDK: Javascript snippet

**Expected behavior**

On page load, it should send the tracking request to dc.services.visualstudio.com

**Additional context**

The default script source of `https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js` still references 2.5.9.

**Comment by MSNev** [comment]
Hi @microsoft/causal-inference 

Can you please try using the updated snippet on the main readme here (https://github.com/Microsoft/ApplicationInsights-JS#snippet-setup-ignore-if-using-npm-setup) as the link provided is still using version 4 (see the sv: "4" value in the snippet) as v4 contains a bug #1402 while the readme version (sv: "5" contains the fix).

And on ai.2.min.js still pointing the v2.5.9, this is by design (see https://github.com/microsoft/ApplicationInsights-JS/milestone/45) as we released v2.5.10 a little too late to avoid the holiday season, the current plan is to change the primary version in the first week of  Jan.

**Comment by leniency** [comment]
Aha - I think I see what's happening. There's a delay in sending telemetry that wasn't happening in 2.5.9. This occurs in both the `sv:4` and `sv:5` versions. I was being impatient in testing.

**Comment by MSNev** [comment]
Ok, I'm glad that the data is still flowing. I just went through all of the changes between 2.5.9 and 2.5.10 and I couldn't see anything specific that would cause a delay with the sending of telemetry -- so I'm not sure what might be causing that situation.

It would be good to better understand that (just in case there is a new dependency that's doing something odd), but failing that it seems we can close this issue?

**Comment by leniency** [comment]
Yeah I think close for now.
