### ISSUE TITLE
Is there a way to get all entries including Ajax Controls and all to browserTimings table

### ISSUE THREAD

**Issue by keyurdev7** [microsoft/ApplicationInsights-JS#1450]
Currently using this SDK we are not getting Ajax controls and all request to browserTimings table we are only getting http:// request. is there any way to track them ?

**Comment by MSNev** [comment]
Hi, Can you please provide some more information, like
- How are you consuming the SDK (via SDK / NPM)
- What is the runtime / browser / version you are using
- By Default the SDK will intercept XMLHttpRequests (if available -- depends on your runtime) unless you disable it via the "disableAjaxTracking"

Is the client attempting to send the requests (use the F12 developer console), and/or try using the browser based debug plugin extension (https://github.com/microsoft/ApplicationInsights-JS/tree/master/extensions/applicationinsights-debugplugin-js) which can be used to help identify and diagnose telemetry issues.

**Comment by keyurdev7** [comment]
How are you consuming the SDK (via SDK / NPM)
==NPM
What is the runtime / browser / version you are using
== angular cli 8 / crome / angular 8

**Comment by MSNev** [comment]
If you are using the fetch() API instead of XMLHttpRequest's you will need to enable fetch tracking by setting the config entry "disableFetchTracking" during initialization to false (it defaults to true -- don't track fetch calls) - https://github.com/Microsoft/ApplicationInsights-JS#configuration.

If you want to have the additional timings for the Ajax (XHR / fetch) calls you can also enable the "enableAjaxPerfTracking" (defaults to false), this will attempt (wait) for the browser to populate the resource timings (note: not always available) and will report the available timings with the Ajax request (includes DNS, redirect etc) -- https://github.com/microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-dependencies-js/src/ajaxRecord.ts#L60

For the main page view we don't currently report the full set of possible values only the basic ones
https://github.com/microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/Telemetry/PageViewPerformanceManager.ts#L30 -- there is a current bug the network time #1440

Have you tried the debug plugin yet? 
As I believe this would be helpful in your case (Angular / Chrome) based

**Comment by keyurdev7** [comment]
Thanks for the detailed information I tried everything but in browserTimeing Table we are only getting http:// request and not any other. Do you have any more thoughts on that ?

![image](https://user-images.githubusercontent.com/60444224/103729611-d811c080-5006-11eb-9737-a2624507df58.png)

pageView table has these many entries

![image](https://user-images.githubusercontent.com/60444224/103729656-ef50ae00-5006-11eb-8aa3-f6b245f3d310.png)

I tried debug plugin as well but it does not helped

Please let me know if you have any more idea

Thanks

**Comment by MSNev** [comment]
The browserTimings table only includes the initial page load, for the additional dependencies they *should* be in the "dependencies" table as a custom JSON blob field as the UX and backend doesn't have separate db fields for these optional values.

On only getting http:, if your using IE then this is a know issue that we worked around for :443 port only as we would not get told (by navigator) that when using :4200 it's also using https:

https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCommon/src/Util.ts#L749
and https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCommon/src/Util.ts#L700

If your using chrome / FF or edge (original or Chromium) then this issue doesn't not occur and we would get https://localhost:4200/ from the navigator object. 
In this case what is the raw value that is sent to the backend (in the track call) -- using either the debug plugin or F12 dev tools - Network tab? -- it *should* be https://localhost and if it is I'll need to create an issue with the backend team to track it down -- but I believe they just treat this as a string field...
