### ISSUE TITLE
[BUG] GDPR - Cookie Management

### ISSUE THREAD

**Issue by VGBenjamin** [microsoft/ApplicationInsights-JS#1463]
**Description/Screenshot**
First of all, I didn't have found a document to guide the developers to the steps to do to respect GDPR when using App Insight on the client side. For example I think that all the tracking cookies (ai_user and ai_session) should be removed when the user only accept the essential cookies.

So I tried multiple stuffs by myself but the cookies are never removed.

**Steps to Reproduce**
Scenario 1:
When the app insight script is initializing: 
```
{
        instrumentationKey: "@Model.InstrumentationKey",
        isCookieUseDisabled: false,
        isStorageUseDisabled: false,
        enableSessionStorageBuffer: false
}
```
But the cookie still remain.

Scenario 2:
Just after the initialization:
```
window.appInsights.clearAuthenticatedUserContext();
```

But again the cookie still remain.

 - OS/Browser: Chrome
 - SDK Version [e.g. 22]: 2.15
 - How you initialized the SDK:
```
<script type="text/javascript">
var sdkInstance="appInsightsSDK";window[sdkInstance]="appInsights";var aiName=window[sdkInstance],aisdk=window[aiName]||function(e){function n(e){t[e]=function(){var n=arguments;t.queue.push(function(){t[e].apply(t,n)})}}var t={config:e};t.initialize=!0;var i=document,a=window;setTimeout(function(){var n=i.createElement("script");n.src=e.url||"https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js",i.getElementsByTagName("script")[0].parentNode.appendChild(n)});try{t.cookie=i.cookie}catch(e){}t.queue=[],t.version=2;for(var r=["Event","PageView","Exception","Trace","DependencyData","Metric","PageViewPerformance"];r.length;)n("track"+r.pop());n("startTrackPage"),n("stopTrackPage");var s="Track"+r[0];if(n("start"+s),n("stop"+s),n("setAuthenticatedUserContext"),n("clearAuthenticatedUserContext"),n("flush"),!(!0===e.disableExceptionTracking||e.extensionConfig&&e.extensionConfig.ApplicationInsightsAnalytics&&!0===e.extensionConfig.ApplicationInsightsAnalytics.disableExceptionTracking)){n("_"+(r="onerror"));var o=a[r];a[r]=function(e,n,i,a,s){var c=o&&o(e,n,i,a,s);return!0!==c&&t["_"+r]({message:e,url:n,lineNumber:i,columnNumber:a,error:s}),c},e.autoExceptionInstrumented=!0}return t}(
{
        instrumentationKey: "@Model.InstrumentationKey",
        isCookieUseDisabled: @accept,
        isStorageUseDisabled: @accept,
        enableSessionStorageBuffer: @accept
}
    ); window[aiName] = aisdk, aisdk.queue && 0 === aisdk.queue.length && aisdk.trackPageView({});

</script>
```

**Expected behavior**
Cookie should be removed

**Comment by MSNev** [comment]
If you don't have consent then you should be setting the "isCookieUseDisabled" to true, in which case the SDK won't read or add the ai_user and ai_session cookies and the Util.deleteCookie also won't delete them either as this controls whether AI can do anything with cookies.

Note: Enabling and disabling cookie usage does not explicitly delete these cookies, it just blocks their creation / usage etc.

The setAuthenticatedUserContext() and clearAuthenticatedUserContext() use the cookie 'ai_authUser' and clearing will (or should -- depending on the above config) delete this cookie only.

The current side effect of setting the "isCookieUseDisabled" is that once disabled there is (currently) no clean way to re-enable cookie support (after AI is initialized). I'm currently working on a branch to rework all of the cookie handling so rather than being globally managed (as it is today) it can be managed and controlled at the instance level -- simplistically so you can enabled / and disable cookie management on the fly -- cleanly -- My current target for a release with this change is the end of Feb release -- all going well with coding, testing and reviews etc.

Even with this change any pre-existing ai_user and ai_session cookies won't be deleted

Additionally, the "isStorageUseDisabled" is not really required as the cookie config "isCookieUseDisabled" controls whether we are "allowed" use the data. So even if there are any pre-existing values in storage we should be ignoring them -- they may still be written (I've only gone over the read path recently and not the write execution path), if you also want to block storage then the value for this config should be "true" to disable usage.

I've added a note in the main Cookie Issue that I'm using to track my changes #1091.

But I believe the above should provide you with the guidance you are looking for?
If not feel free to ask for more info here.

**Comment by VGBenjamin** [comment]
Thanks a lot for those information, Yes, it wasn't intuitive that those method didn't delete the cookie but still really disable it. SO I guess that I could keep it as I did: is the isCookieUseDisabled to true and I have removed the cookie manually even if as you say it is in fact useless.
As I am not in a one page application the side effect you mention with the reenabling of the cookie is not too much an issue for me because on the next page load it will be ok again. It just have the side effect to not track the current page just after reenabling the cookies.
Thanks a lot for your precious help!
