### ISSUE TITLE
Is there a way to disableAjaxTracking for specific ajax requests

### ISSUE THREAD

**Issue by thoo1** [microsoft/ApplicationInsights-JS#1472]
**Is your feature request related to a problem? Please describe.**
I want to be able to manually log to dependencies table for some requests for my app, for parts of the app that I can control. I would also like to keep the automatic ajax tracking for other requests of my app.

When I manually log, I would like to turn off the automatic logging that app insights sdk does, so that I do not get two logs for the same api call.

**Describe the solution you'd like**
A flag or something I can pass in the XHR object that disables the automatic logging. Or any other solution

**Describe alternatives you've considered**
Accomplishing this by monkey patching xhr to read some dummy header that flags to the telemetry initializer to not log the automatically collected log.

**Additional context**

**Comment by MSNev** [comment]
This depends on the URL you are using.

There is an "internal" property which we use to tag XHR and fetch requests to our backend domains so that we don't end up in a loop.

And for performance, once a domain has been identified as Disabled ALL requests to that domain (even without the flag) will NEVER be instrumented

The code for the flag is here https://github.com/microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-dependencies-js/src/ajax.ts#L532

But as I said above this is designed as an *internal* switch, so there are no guarantee's that mechanism is not changed in the future (at which point you would be broken).

**Comment by thoo1** [comment]
I see, thanks for that. Do you think this could be a feature that is supported? The `xhr[DisabledPropertyName] = true` would work for my use case.

Our situation is that we want to keep the app insight auto logging on for all requests that are outside our code's control (to make sure we don't drop any logs and get a full picture of api calls being made). At the same time, we want to have custom dependency logging for code that we do control, but we dont need a duplicate log from app insight's auto logging

**Comment by MSNev** [comment]
Tagging this as an enhancement, to be able to configure which URL's are tracked -- I actually thought we had this already but I'm probably mis-remembering or something.

**Comment by MSNev** [comment]
Reopening for release tracking

**Comment by xiao-lix** [comment]
> Reopening for release tracking

oops... sorry I thought this was released. 😅

**Comment by MSNev** [comment]
Actually, it looks like it might be as the commit was in June -- which means it probably got missed in the release notes for the July release @xiao-lix can you please check and if it's not in the release notes lets update them and then re-close this issue

**Comment by xiao-lix** [comment]
@MSNev it should be included in this release - https://github.com/microsoft/ApplicationInsights-JS/releases/tag/2.6.4
I updated the release notes. Re-close this issue.
