### ISSUE TITLE
[BUG] trackPageViewPerformance method is not logging any information in App Insights (Spfx-React)

### ISSUE THREAD

**Issue by johnvittneyk** [microsoft/ApplicationInsights-JS#1486]
**Description/Screenshot**
trackPageViewPerformance method is not logging any information in App Insights

**Steps to Reproduce**
1) Install @microsoft/applicationinsights-web in SPFx webpart for capturing telemetry (Refer below to understand initialization)
2) Instantiate Logging object from Webpart tsx file, This triggers the **trackPageViewPerformance** method in the constructor

 - OS/Browser: Edge
 - SDK Version [e.g. 22]: 2.5.11
 - How you initialized the SDK: 

**Logging.ts File**
```
import { ApplicationInsights } from '@microsoft/applicationinsights-web'

export enum EventType {
	Information = "Information",
	Error = "Error",
	Exception = "Exception",
	Request = "Request",
	PageViewPerformance = "PageViewPerformance"
}

//Authenticating AppInsights
export class Logging {
	private static userAlias: string;
	private static appInsights: ApplicationInsights;

	constructor(alias: string, pageViewName: string) {
		Logging.userAlias = alias;
		Logging.appInsights = new ApplicationInsights({
			config: {
				instrumentationKey: appInsightsKey,
				disableExceptionTracking: true,
				/* ...Other Configuration Options... */
			}
		});

		Logging.appInsights.loadAppInsights();

		let pageViewProps = {
			'name': pageViewName,
			'properties': {
				'Url': window.location.href,
				'Alias': alias,
				'DocumentTitle': document.title,
				'uri': location.href
			}
		}

		Logging.appInsights.trackPageView(pageViewProps);

		let pageViewPerformanceProps = {
			'name': pageViewName + "_Performance",
			'properties': {
				'Url': window.location.href,
				'Alias': alias,
				'DocumentTitle': document.title,
				'uri': location.href
			}
		}

		**Logging.appInsights.trackPageViewPerformance(pageViewPerformanceProps)**
	}

```
HelloWorld.tsx file (Webpart File)

```
import { Logging, EventType } from '../../../utilities/Logging';


export default class HelloWorld extends React.Component<IHelloWorldProps, {}> {
  private logging: Logging;
  constructor(props: IHelloWorldProps) {
    super(props);
    this.logging = new Logging(this.props.loginName, 'Testing Telemetry Methods');
    Logging.AppInsightsTrackTrace("HelloWorld.tsx","Test Component","Constructor",EventType.Information,"Constructor","Exiting: Constructor","No Control ID","URL Test")
  }
  public ClickAction(){
    alert("Well, Log is Triggered");
    Logging.AppInsightsTrackTrace("HelloWorld.tsx","Test Component","ClickEvent",EventType.Information,"ClickAction","Entering: User Clicked on the link","No Control ID","URL Test")
    Logging.AppInsightsTrackEvent("HelloWorld.tsx","Test Component","ClickEvent",EventType.Information,"ClickAction","User Clicked on the link","No Control ID","URL Test")
    Logging.AppInsightsTrackTrace("HelloWorld.tsx","Test Component","ClickEvent",EventType.Information,"ClickAction","Exiting: User Clicked on the link","No Control ID","URL Test")
    alert("Now, go Check for Trace and Event in Logs");
  }
  
  

```

**Expected behavior**
**Logging.appInsights.trackPageViewPerformance(pageViewPerformanceProps)** methods logs information in the App Insights

**Additional context**
We are able to see logs for **Logging.appInsights.trackPageView(pageViewProps);** method but not for **Logging.appInsights.trackPageViewPerformance(pageViewPerformanceProps)** method

**Comment by xiao-lix** [comment]
Thanks for reaching out @johnvittneyk, I needto clarify some points you described: 
1. Since you mentioned SPFx, are you using SharePoint site? According to the doc, it's recommended to use [SPFx to build a custom extension](https://docs.microsoft.com/en-us/azure/azure-monitor/app/sharepoint) to install AI on your SP sites. And here're two samples : [1](https://github.com/pnp/sp-dev-fx-extensions/tree/master/samples/js-application-appinsights). [2](https://github.com/pnp/sp-dev-fx-extensions/tree/master/samples/js-application-appinsights-advanced).
2. You are saying that you see pageView log but not for pageViewPerformance. But I see you called the two methods in the same file. Can you please try setting break points on these methods and confirm both are called? Do I understand correctly that the methods are called but one has log the other doesn't ? These two methods are exported in the same file.
3. Do you see any error message in the console? 
4. How do you check the logs, through azure portal or Network tab? 
5. Maybe this is not related but what does Logging.AppInsightsTrackTrace/Logging.AppInsightsTraceEvent do?
