### ISSUE TITLE
In Page View its not showing which API called on particular page.

### ISSUE THREAD

**Issue by jitendraP-ashutec** [microsoft/ApplicationInsights-JS#1491]
I am using this package in nativescript angular. Initially it was not working so I have made some changes and created custom local package https://github.com/microsoft/ApplicationInsights-JS/issues/1459#issuecomment-777992872.  

but now in Page View page its not showing which API called on particular page.

could you please suggest me what changes  I need to require.

**Comment by xiao-lix** [comment]
hi @jitendraP-ashutec , looks like you need to pass in the refUri yourself. Because it either takes the document title or location href, but nativescript doesn't have those passed in, so it's empty: please refer to the implementation [here](https://github.com/microsoft/ApplicationInsights-JS/blob/3d4a6fa42a7a25ceedbf3131598819249797ad47/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/Telemetry/PageViewManager.ts#L81). 
Thus, you could pass it in as how it does in react plugin [here ](https://github.com/microsoft/ApplicationInsights-JS/blob/ae71ebf806da82e149b0af60f00d70b2c1d3e3f0/extensions/applicationinsights-react-js/src/ReactPlugin.ts#L40)and [here](https://github.com/microsoft/ApplicationInsights-JS/blob/ae71ebf806da82e149b0af60f00d70b2c1d3e3f0/extensions/applicationinsights-react-js/src/ReactPlugin.ts#L97).

**Comment by jitendraP-ashutec** [comment]
Thanks for your response @xiao-lix .

I tried to set uri and refuri in trackPageView call. and I can see refuri is set in Custom Properties. But still it  I can not see API call is co relate to particular page. It log differently API call and page view. but it is now showing API call under PageView.

One thing I notice that  in website where this is working.

There is Page View Properties exist in Page View and API call.

But when I see in nativescript data, there is no Page View Properties in API call, its only exist in Page View.

I have set like:
```

**Comment by xiao-lix** [comment]
hi @jitendraP-ashutec , I'm not sure I understand your question. Can you please elaborate more? Is the "API call" happening on the same pageview? By default, the Application Insights SDK for JavaScript creates a new operation for each unique page view. And the requests happening on the same pageview (share the same operation id) are correlated. Check the correlation doc [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation#data-model-for-telemetry-correlation).

**Comment by jitendraP-ashutec** [comment]
Yes API call is happen in same pageview.

Lets say...  I have dashboard page and in dashboard page I am calling /dashboard API to get data. so in web  when I see pageview for dashboard then show that /dashboard API called. 

but on Nativescript mobile app it is not working. It is not showing on /dashboard API when I see pageview for dashboard.

@xiao-lix

**Comment by xiao-lix** [comment]
@jitendraP-ashutec If I understand correctly, are you setting the traceId/operationId by yourself? You may need to generate the trace id on your pageview yourself. Can you try something like [this](https://github.com/microsoft/applicationinsights-angularplugin-js/blob/3262896ac2ef875dc1bc59e59e72492c752f542c/projects/applicationinsights-angularplugin-js/src/lib/applicationinsights-angularplugin-js.component.ts#L86-L88). And by the way, you are seeing request telemetry but just not correlate as expected right?

**Comment by jitendraP-ashutec** [comment]
@xiao-lix  Thanks for response. Let me try your suggestion. 
Yes,  I am able to see API but it is not correlate with in pageview.

**Comment by jitendraP-ashutec** [comment]
@xiao-lix  do you have any plan to create package for nativescript like you created for angular ?
