### ISSUE TITLE
[BUG] Impossible to track fetch request when binding to window

### ISSUE THREAD

**Issue by jf-niji** [microsoft/ApplicationInsights-JS#1494]
**Description/Screenshot**
We got an HTTP client class which use fetch to do HTTP request in Vue.js app. We bind fetch to window `window.fetch.bind(window)` (See Steps to Reproduce for the class) to enable fetch to be performed. Fetch requests are not tracked because of this bind.

When I do simple fetch by not using this HttpClient class, fetch request are tracked.

**Steps to Reproduce**

1. Install package in project and init it with fetch tracking
2. Do request with fetch binded to window

 - OS/Browser: Windows / Chrome
 - SDK Version [e.g. 22]: Latest
 - How you initialized the SDK: 

```import { ApplicationInsights } from '@microsoft/applicationinsights-web'

const AppInsightsPlugin = {
	install(Vue, options) {
		// Using AppInsights to detect error in production only
	//	if (process.env.NODE_ENV === 'production') {
		const appInsights = new ApplicationInsights({
			name: 'dsfAppInsights',
			config: {
				instrumentationKey: process.env.VUE_APP_APP_INSIGHTS_KEY,
				disableFetchTracking: false, // Track API HTTP call
				disableAjaxTracking: true, // Do not track assets or other stuff
				enableCorsCorrelation: true,
				enableRequestHeaderTracking: true,
				enableResponseHeaderTracking: true,
				enableAjaxPerfTracking: true,
				appId: process.env.VUE_APP_APP_INSIGHTS_ID,
			},
		})

		appInsights.loadAppInsights()

		// Send trackPage at each page change
		options.router.beforeEach((to, from, next) => {
			appInsights.trackPageView({
				name: to.name,
				uri: to.path,
			})

			next()
		})

		// Track root page
		// Router is initiliazed before appInsights, so beforeEach hook is already call when appInsights is initialized
		appInsights.trackPageView({
			name: options.router.currentRoute.name,
			uri: options.router.currentRoute.path,
		})

		// Attach custom properties to each tracking
		appInsights.addTelemetryInitializer((envelope) => {
			let telemetryItem = envelope.baseData

			telemetryItem.properties = telemetryItem.properties || {}

			telemetryItem.properties['front:application'] = options.appName
			telemetryItem.properties['front:path'] = options.router.currentRoute.path
			telemetryItem.properties['front:url'] = window.location.href
			telemetryItem.properties['front:version'] = process.env.VUE_APP_VERSION
		})

		Vue.config.errorHandler = (err, vm, info) => {
			Vue.prototype.$logger.error(err, {
				'front:vue': {
					componentName: vm.$options.name,
					lifecycleHook: info,
					propsData: vm.$options.propsData,
				},
			})
		}

		Vue.prototype.$logger = {
			error: (exception, properties = {}) => {
				appInsights.trackException({
					exception: exception,
					properties: properties,
				})
			},

			info: (message, properties = {}) => {
				appInsights.trackTrace({
					message: message,
					properties: properties,
				})
			},
		}
	},
//	},
}

export default AppInsightsPlugin
```

My HttpClient class:
```
class HttpClient {
	constructor() {
		this._httpClient = window.fetch.bind(window)
	}

	get(url, headers) {
		return this._httpClient(url, {
			method: 'GET',
			headers: headers,
		})
	}

	post(url, headers, body) {
		return this._httpClient(url, {
			method: 'POST',
			headers: headers,
			body: body,
		})
	}

	put(url, headers, body) {
		return this._httpClient(url, {
			method: 'PUT',
			headers: headers,
			body: body,
		})
	}

	patch(url, headers, body) {
		return this._httpClient(url, {
			method: 'PATCH',
			headers: headers,
			body: body,
		})
	}

	delete(url, headers) {
		return this._httpClient(url, {
			method: 'DELETE',
			headers: headers,
		})
	}
}

export default new HttpClient()
```

Doing fetch request : 
```
import HttpClient from './HttpClient'

const response = await HttpClient.get('my_url', {}) // /!\ Not tracked
```

**Expected behavior**

Fetch request are tracked

**Comment by MSNev** [comment]
Without attempting a repro, the first thing that comes to mind is that *if* the HttpClient class is created before the Application Insights is initializaed then the bind operation will be grabbing a copy of the default fetch function entry points, which therefore won't be tracked. Why? During AI initialization we hook (wrap) the fetch call with our own hook methods so that we can execute code before sending, and after a response (or error) is received, if your proxy the call before we install this hook then nothing will be tracked as we don't know that it's occurred.
i.e
let httpClient -> bind (proxy) fetch. 
- Calls path would become: httpClient -> original fetch
let AI.initialize() -> wrap fetch
- Calls to fetch become fetch -> AI Wrapped fetch -> original fetch
- Calls to httpClient remain unchanged: httpClient -> original fetch
If AI is initialized first then the binding *should* pickup and proxy to the AI wrapped fetch instance.

Question: As you binding to window, why not just call window.fetch rather than creating your own local variable? Depending on the scope of your script you may also just be able to access fetch directly as a global which in both cases would pickup the AI instrumented (wrapped) version of fetch...

**Comment by MSNev** [comment]
@jf-niji Did the above resolve or help with the issue?

**Comment by MSNev** [comment]
Assuming this resolved the issue -- closing, please comment again if it didn't
