### ISSUE TITLE
[BUG] applicationinsights-web npm package does not have types or a types folder. 

### ISSUE THREAD

**Issue by ShayanZafar** [microsoft/ApplicationInsights-JS#1496]
reproduce:

 npm i --save @microsoft/applicationinsights-web

navigate to node_modules/@microsoft/applicationinsights-web

no types folder with typings. other folders have it. wondering why this project is missing typings?

is there a workaround or some other typings i can point to?

**Comment by MSNev** [comment]
There are a couple of issues here
- The types are actually (currently) being generated in the dist-esm folder (so they are present)
- The package.json is pointing the the types folder (just like all of the others -- looks like a copy paste issue)

Solutions
- try referencing the dist-esm folder (will fix this as part of this issue)
- As part of the next release we are now generating complete (single file) *.d.ts as part of the fix for #1473 

Will keep this issue open to "fix" the package.json reference and where the files are being dropped.

**Comment by MSNev** [comment]
v2.6.0 is now fully deployed to all CDN endpoints
