### ISSUE TITLE
What's the issue if we use Snippet and NPM setup at the same time?

### ISSUE THREAD

**Issue by JacksonHong** [microsoft/ApplicationInsights-JS#1507]
According to the documentation, we are not supposed to use Snippet and NPM setup at the same time.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript

![image](https://user-images.githubusercontent.com/11079437/112224788-0b68f200-8be9-11eb-8729-80a8df84ddbb.png)

Our service runs behind a reverse proxy which injects a "shell" for some common headers and styles. In the shell they inject, they are using the Snippet setup to initialize Application Insights and we use the NPM setup in our Angular app to initialize a new instance of Application Insights.

We noticed that we are not getting all client side logs in our Application Insights. Our various APIs losses anywhere from 20% to 99% of the logs.

I'd like to know if this could be due to using both the Snippet as well as NPM setup and if so what do you recommend to workaround this?

**Comment by MSNev** [comment]
Technically, Its possible, but it depends a lot on how things are used and initialized 

For example 
- if as part of the common headers they are initializing the global instance with their iKey for all automatic events then they will get those (as expected)
- If you are using NPM to initialize application insights AND only use your initialized instance (via a local variable) then you will get all of your events including page view etc 
The above work because you each have your own references.

An issue comes about however, if both of you are initializing, using  and setting the global instance (by default `appInsights` or (`window.appInsights`)), in this case you will have a race condition about who sets the global instance last and at that point all references are going only to that instance and iKey.

The main reason for the notice is size, as you will have the AI code getting downloaded from the CDN and included by your packages (assuming downloaded via CDN also).

To avoid this either (or both) of you should change the "global" name that you are using for the instance that you are using.

For the snippet that is what this config is for (with the current snippet)
> // name: "appInsights", // Global SDK Instance name defaults to "appInsights" when not supplied

And for NPM users either ensure that the following is run within a closure (or your own module etc) or just change the name from appInsights to avoid a name clash.
> const appInsights = new ApplicationInsights({ config: {

**Comment by JacksonHong** [comment]
Thanks for the quick response. I checked and confirmed that we are not using the same global instance, `appInsights` or `window.appInsights`. The issue must be somewhere else then. I'll keep digging.

**Comment by MSNev** [comment]
Closing this issue as I think we have answered this question, if you find something specific please open a new issue.
