### ISSUE TITLE
Does this sdk support tracking script requests?

### ISSUE THREAD

**Issue by thoo1** [microsoft/ApplicationInsights-JS#1539]
**Is your feature request related to a problem? Please describe.**
In our SPA application, we load other javascript bundles asynchronously after our application loads.
It would be great if this SDK could track these bundle loads and their status, size, and other timings

**Describe the solution you'd like**
Something very similar to the automatic dependency tracking that this sdk already supports

**Describe alternatives you've considered**
If not, we are thinking of just using the resource timing api to get this info https://developer.mozilla.org/en-US/docs/Web/API/Resource_Timing_API, we'd have to code it ourselves, it'd be great if it came out of the box 

**Additional context**

**Comment by MSNev** [comment]
No it doesn't and it's not generally an available feature across all browsers.
The only way to "monitor" the status of a script tag is to directly include onload/error event handlers (which is what the snippet (since v4) does to track if the SDK was downloaded from the CDN).

I do have an internal investigation (not currently an issue on GitHub) to look at adding the loaded scripts as part of the exception details.

Enumerating the resource timings is an interesting approach for those browsers that support it and it does sound like a potential additional "extension" to trigger some form of custom event for each script... 

It will either need to create a timeout to call back (after page load) or just wait for some period....

**Comment by thoo1** [comment]
sounds good @MSNev
For now I've accomplished listening to timing/size info for script loads using PerformanceObserver api, which like you said, isn't generally available to all browsers

Like you said, seems like getting the status of the script load isn't expose in the performance timing apis - it is only on the load/error event handlers

**Comment by MSNev** [comment]
I've created a new issue #1547  with this as a feature request, if you want to turn your solution into a new extension this would be the issue to use. Feel free to ping me internally for any guidance if needed.
