### ISSUE TITLE
[BUG] React Native - Is it possible to set the UserID to the Internal UserID used by our app

### ISSUE THREAD

**Issue by SirElTomato** [microsoft/ApplicationInsights-JS#1575]
Something like this "appInsights.setAuthenticatedUserContext(validatedId, accountId);"

https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#authenticated-users

So that we can track our users journey using application insights 'Users' blade under the usage tab of Application Insights 

We are using React Native mobile app and .Net Framework web apis

**Comment by MSNev** [comment]
Yes, you can...

I'm not sure if your asking a question or identifying a bug as the ```setAuthenticatedUserContext``` function is available on the main ```appInsights``` instance and the ReactNative plugin is just an extension you add to the existing...

So after you initialize (loadAppInsights()) the SDK you can (or should be able to) call the function as you outline
```appInsights.setAuthenticatedUserContext(validatedId, accountId);```

**Comment by richshepard** [comment]
@MSNev Thanks for that, I was assuming this didn't work for two reasons, the first is because of this posted under the AppCenter repo (I was assuming the base code would eb the same):

https://github.com/microsoft/appcenter-sdk-react-native/issues/503

I also tried using the call and setting the user id to tomething like "Test" and then tried running the following query after I knew the record was in App Insights:

`customEvents
| where timestamp >= ago(2h) and user_Id contains "Test"
| order by  toint(customDimensions["eventTimestamp"])`

It's possible that this test is completely invalid through.
