### ISSUE TITLE
[BUG] Violation of Lighthouse Best Practice — 'Registers an unload listener'

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/ApplicationInsights-JS#1620]
## Description/Screenshot
![image](https://user-images.githubusercontent.com/1106823/127900162-c651ab20-3e46-4d2f-9e2f-2b6ca1f4a8bc.png)

## Steps to Reproduce

 - OS/Browser: Chrome
 - SDK Version [e.g. 22]: The script being loaded is this one: https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js
 - How you initialized the SDK: Using custom code

1. Open up a web page that loads AI.
2. Open up Chrome Developer Tools (F12)
3. Switch over to the Lighthouse Tab.
4. Click 'Generate Report'. I ran this for device 'Mobile'.
5. After the report completes, click on 'Best Practices' and then the violation is reported under 'General'.

## Expected behavior
No violation

## Additional context

Clicking on 'Learn More' takes you to this page: https://developers.google.com/web/updates/2018/07/page-lifecycle-api?utm_source=lighthouse&utm_medium=devtools#the-unload-event

**Comment by MSNev** [comment]
We register and listen to "unload", "beforeunload", "pagehide" and "visibilitychange" (this last one as of last release).

We need to listen to all possible events to support the full browser matrix and not just more modern browser that support the other events. As such we NEED to continue listening to the unload event so that we can flush any unsent event in ALL browsers.

**Comment by NoelAbrahams** [comment]
Interesting argument. We also load Google Analytics and Google Analytics 4. 

No violations there.

**Comment by MSNev** [comment]
Their support browser matrix is a lot smaller than ours https://support.google.com/analytics/answer/3541880?hl=en

**Comment by NoelAbrahams** [comment]
@MSNev that refers to browsers one can use to access the analytics _dashboard_. Of course the script itself will work on all versions of all browsers.

> We register and listen to "unload", "beforeunload", "pagehide" and "visibilitychange"

This sounds like an expensive way to do things. Should be based on feature detection.

**Comment by MSNev** [comment]
We effectively are performing a lightweight form of feature detection __if__ the event is available we hook it, otherwise we don't.
This is much more lightweight than having a more complete feature detection with feature tables identifying what can and can't be done and then causing additional testing and deployed dead code (for some browsers) due to multiple branches etc.

So [this is the entire attach code required](https://github.com/microsoft/ApplicationInsights-JS/blob/975060af9f1aa53e8a1376bdac992ed68f0e0e0f/shared/AppInsightsCore/src/JavaScriptSDK/HelperFuncs.ts#L67-L86) and and it's [effectively called this 4 times](https://github.com/microsoft/ApplicationInsights-JS/blob/master/AISKU/src/Initialization.ts#L496-L501) this also attempts to list to the event at the window, body and document level, again this is to support all of the legacy browsers and platforms as not all support the events at the window level

Some of this is more complex than we would like, but it is required as we are providing support for IE 8+ with active end-user customers still actively using IE8 (and in some cases IE7 😥 ).
