### ISSUE TITLE
[BUG] customProperties parameter missing from trackException function

### ISSUE THREAD

**Issue by devin5885** [microsoft/ApplicationInsights-JS#1647]
**Description/Screenshot**
In some places the trackException function includes the customProperites parameter, in other places it does not. Without this parameter it does not seem to be possible to pass custom properties when logging an exception.

**Steps to Reproduce**
n/a

 - OS/Browser: Windows 10/Chrome
 - SDK Version [e.g. 22]: latest
 - How you initialized the SDK: yes
n/a

**Expected behavior**
trackException should include this parameter in all cases.

**Additional context**

**Comment by MSNev** [comment]
Looks like it is missing from the ```AISKU/src/Initialization.ts``` version, not seeing anything obvious as to why this was not included in this version.

It's specifically not included in the ```AISKU/src/ApplicationInsights/Deprecated.ts``` due to backward compatibility using the older snippet and upgrading from v1.

Tagging this issue as a Bug so we add the additional customProperties?: ICustomProperties to ```Initialization``` only

**Comment by MSNev** [comment]
v2.7.0 is not fully deployed to NPM and all CDN endpoints
