### ISSUE TITLE
[BUG] enableUnhandledPromiseRejectionTracking shows no error trace 

### ISSUE THREAD

**Issue by Karlie-777** [microsoft/ApplicationInsights-JS#1679]
when parsing `onunhandledrejection` error event, `error.reason.toString()` is passed to `Exception.CreateAutoException()` function and the `error.reason.toString()` will expose no detailed trace stack . Instead `error.reason.stack.toString()` should be used to enable full trace tracking.

**Comment by Karlie-777** [comment]
linked to issue: https://github.com/microsoft/ApplicationInsights-JS/issues/1675

**Comment by nika1001** [comment]
hi @Karlie-777 , is there any update on this bug please? We are also not seeing any stack trace with enableUnhandledPromiseRejectionTracking enabled, SDK version is 2.7.3.
Rejected promise is correctly logged but with no stack information. Inspection of PromiseRejectionEvent shows that stack is under reason prop but is not parsed by _getStackFromErrorObj:
![image](https://user-images.githubusercontent.com/22968705/188440441-ee2d3577-57e3-4481-8a2a-90350983ed8e.png)

**Comment by Karlie-777** [comment]
@nika1001 please try the latest version 2.8.5+ since we have some updates in new version. And also when full error trace is not available, error stack will be not parsed.

**Comment by MSNev** [comment]
@nika1001 FYI - the fix is now checked in and the automated pre-release night build has been published with #1900, so you should be able to pre-validate that this fixes your issue by simply using the "@nightly" build as the version.
The full nightly release night build is [nightly-2209-02](https://www.npmjs.com/package/@microsoft/applicationinsights-web/v/2.8.8-nightly.2209-02)
