### ISSUE TITLE
Preventing certain pages from being track or stripping out query string

### ISSUE THREAD

**Issue by PhillipZada** [Microsoft/ApplicationInsights-JS#173]
Hi,

I was wondering is there the ability to prevent certain pages from being track in a SPA. The situation I have is that we are using and angular App with an OpenId server that redirects the user with the id_token and access_token in the url path (as per w3c specs), we've noticed that app insight is sending the tokens to the telemetry tracking. How can we prevent/block/rewrite this?

**Comment by AlexBulankou** [comment]
Try telemetry initializer for JS SKD:https://blogs.msdn.microsoft.com/albulank/2016/04/20/modifying-and-filtering-telemetry-with-appinsights-javascript-sdk-telemetry-initializer/ Does this help with your scenario?

**Comment by phillsta** [comment]
Yep thats perfect! Managed to check the url path and censor as per the example. 

The only issue arising with this is that the URL_LONG error about truncation still comes up and this might raise concern with the customer about vulnerability. Not a big deal just thought I'd ask if there is a potential workaround to stop this.

**Comment by AlexBulankou** [comment]
Thanks! To clarify, you would like to disable this particular diagnostic warning or disable all warnings? Or you are seeing PII in the URL recorded as part of this warning?

**Comment by PhillipZada** [comment]
Either one for the warnings, below is the warning I'm getting.

```
AI: USRACT_UrlTooLong message:"url is too long, it has been trucated to 2048 characters." props:"{url:https://localhost:45705/login/callback/#id_token...
```

On a side note ( whilst i got you :+1: ) what would recommend be the best method to track time spent on a page? tried the startTrackPage, stopTrackPage calls but that is more around the time it takes to load a page. Would custom events/metric be the best method?

**Comment by AlexBulankou** [comment]
You can use telemetry initializer to disable this particular or all warnings from being sent. Separately I opened #174 to make it easier.
Regarding your other question: manually measuring time spent on page and then using custom metric to record it would be the best option. At this point we are intentionally not investing in out-of-box usage scenarios, and only provide basic tracking of users/sessions that is required for impact analysis. The reason is that AppInsights is about performance and failure diagnostics. For advanced usage we are recommending that customers look into other solutions, such as Google Analytics. However you can use AppInsights to record any metrics, so if you don't require advanced  features, AppInsights client-side instrumentation would be sufficient for both diagnostics and usage.
