### ISSUE TITLE
Enable a setting to disable all or certain types of diagnostic warnings

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-JS#174]
They can be disabled using telemetry initializer, however initializing setting would be easier and less error prone.

**Comment by BlackMael** [comment]
I got here from [this issue](https://github.com/Microsoft/ApplicationInsights-JS/issues/173) as I am having issues with *UrlTooLong* being thrown to the console because of a 3rd party tool (mixpanel.com)
I tried using a telemetry initializer but it seems to me that it doesn't kick in soon enough to hide the warning.
The DataSanitizer kicks in first (calling sanitizeUrl()) and there seems to be no way to override it. It will always log the warning to the console.
I can fiddle with the remote dependency data all I want and even filter the events out, but I'm already too late, the damage is already done by the sanitizeUrl() function. 

Oh! I just noticed the tag *enhancement*... Does that mean this feature is still in the backlog?

**Comment by SandyVeliz** [comment]
Hi! same trouble here, i m doing an app with Angular and B2C, the trouble is that the id_token and the accestoken are informed in the console as warning.

> `AI: StringValueTooLong message:"string value is too long. It has been truncated to 1024 characters." props:"{value:/#state=CientId&client_info=accestoken`.

there is a way to disable this specific warning?

**Comment by barustum** [comment]
@SandyVeliz what release are you on? Per this [issue](https://github.com/Microsoft/ApplicationInsights-JS/issues/566), this has been fixed.

**Comment by barustum** [comment]
I peeked at the [package.json](https://github.com/MarkPieszak/angular-application-insights/blob/master/package.json) for the angular-application-insights library. It seems like they are using the version that doesn't have the fix.

**Comment by SandyVeliz** [comment]
Yes, I checked with my local version and use the same version, I will make a problem in your repository. Thank you so much!

**Comment by MarkPieszak** [comment]
Strangely we have the library setup to use `^1.0.15` which should get the latest (1.0.18 anyway), but I cleaned out the package-lock files, and updated everything to 1.0.18 and republished to npm, so hopefully that does the trick. But that's odd, I would of thought it would of been working either way! 🤔

**Comment by markwolff** [comment]
Closing for now as underlying issue was solved. Reopen if there is still an ask for logging filters
