### ISSUE TITLE
Minified files should be used as entrypoints

### ISSUE THREAD

**Issue by lramos15** [microsoft/ApplicationInsights-JS#1741]
In the web loading times are often critical and therefore loading the minimum amount of data is important. VS Code on the web relies on the appinsights-js module for telemetry, but patches the minified files to be the entrypoint for faster loading. 

**My Proposal**
Replace `"main": "dist/applicationinsights-web.js"` in the package.json with `"main": "dist/applicationinsights-web.min.js"`.  The minified file is less than half the size of the non minified one.

**Comment by MSNev** [comment]
When using the NPM packages we assume that you will also have your own packages minified and this would include anything included via the main or dist-esm.

In the case of VS Code on the web would it make sense to have it download the current version from the CDN (using the snippet) rather than have it included locally in another package?

**Comment by joaomoreno** [comment]
We want to minimize the diversity of request origins, for VS Code on the web.

**Comment by MSNev** [comment]
I've done a bunch of looking around at other project and the standard way appears to be that when using the npm package the assumption is generally that consumers will be using their own packager which may (or may not) including minification. If we change the ```main``` entry point to be the included minified files this would then lead to consumers attempting to minify the already minified files (which is generally not a good idea).

As such and because we include the minified files as part of the npm bundle (in the ```browser``` folder) which now includes a generic non-versioned ```ai.2.min.js``` I don't believe we will or want to make this change.

You should be able to configure your build environment to either
- Minify the 'main' entry point as part of packaging
- ignore the main and link to the ```browser/ai.2.min.js``` version
- Don't use the npm package at all and get the build environment to download the ```current``` version from the CDN (not really ideal as depending on when the build occurs you will end up with a different version eg. attempt to repo an issue with an older baseline etc.) -- So I'm including for completeness and not actually recommending this as a general strategy.

**Comment by lramos15** [comment]
No worries thanks for the investigation we currently use `@microsoft/applicationinsights-web/dist/applicationinsights-web.min.js` 

you can see that in commit https://github.com/microsoft/vscode/commit/a9acf06479370215a716c593ce615cfdd6b81502
