### ISSUE TITLE
Manual logging with opt-in telemetry?

### ISSUE THREAD

**Issue by baxxos** [microsoft/ApplicationInsights-JS#1769]
Hi guys,

I'm trying to utilize this SDK in a way that lets user opt-in into using telemetry by clicking a button located in the cookie consent. However, even if the user declines, I would like to keep sending _some_ essential errors, warnings or debug logs into my Application Insights instance (similar to server logging). Currently, this seems to be impossible since the `disableTelemetry` config option behaves like a global killswitch - i. e. it doesn't even let me do the following:
```js
appInsights = new ApplicationInsights({
      config: {
        instrumentationKey,
        disableTelemetry: true,
        extensions: [reactPlugin],
        extensionConfig: {
          [reactPlugin.identifier]: {
            history: browserHistory,
          },
        },
      },
    })
...
const insights = getAppInsights()
insights.trackException(obj) // does nothing
```

**Describe the solution you'd like**
The `disableTelemetry` should not disable the manual event tracking, or it should provide some kind of state other than globally on/globally off.

**Describe alternatives you've considered**
I've considered keeping the telemetry enabled and disabling all other available configuration options:
```
disableTelemetry: false,
enableAutoRouteTracking: false,
disableCookiesUsage: true,
disableAjaxTracking: true,
disableFetchTracking: true,
```
However, there is no guarantee that the telemetry is indeed disabled (which can have legal implications in some states) and I'm still getting pageView events. 

Am I missing something? Is there some other configuration option I haven't considered?

**Comment by MSNev** [comment]
No, you are correct the `disableTelemetry` is a global switch as from the SDK perspective we would have the same potential legal implications (globally) if we didn't.

If your using NPM instead of the CDN, one option would be to create your own SKU (group of components) which perhaps only included the Core and Sender (there may be other required components that I'm not currently thinking of), but with just these all of the automatic collection code should not be getting instantiated and therefore hooked up.

You can use the new [Chrome Extension](https://github.com/microsoft/ApplicationInsights-JS/tree/master/tools/chrome-debug-extension) to view all of the telemetry that is getting sent from you local instance (during development) or the in-proc [Debug Extension](https://github.com/microsoft/ApplicationInsights-JS/tree/master/extensions/applicationinsights-debugplugin-js).

You can see from the AISKU initialization that this is the default plugins that are added https://github.com/microsoft/ApplicationInsights-JS/blob/master/AISKU/src/Initialization.ts#L143-L148 which is initialized here https://github.com/microsoft/ApplicationInsights-JS/blob/master/AISKU/src/Initialization.ts#L393-L401

So to help here is a quick detail of what these plugins do
- `_self.appInsights = new ApplicationInsights()` (this is all of the "web hooks") -- I'd excluded this one
- `_self.properties = new PropertiesPlugin()` (this accesses a log of the cookies `ai_user` etc and sets a bunch of default common values) -- you may want to include but still set the `disable` properties
- `_self.dependencies = new DependenciesPlugin()` (this is the code that intercepts and tracks XMLHttpRequest and fetch requests) -- you probably want to disable
- `_self.core = new AppInsightsCore()` this is required and you would want to probably expose and call the track method directly for your internal stuff
- `_self.sender = new Sender()` (Required, this is the code the "packages" and "sends" the events to the backend)

**Comment by baxxos** [comment]
@MSNev thanks for a well-written reply. I should be able to move on based on your info 👍

**Comment by baxxos** [comment]
@MSNev - I'm sorry to hijack this issue, but I seemingly can't make the `disableCookiesUsage` option work. I'm using the following package versions:
```
"@microsoft/applicationinsights-common": "^2.7.3",
"@microsoft/applicationinsights-react-js": "^3.2.3",
"@microsoft/applicationinsights-web": "^2.7.3",
```
What's weird is that no other cookie-related option seems to work for me either - I've tried disabling all of them, yet the `ai_user` and `ai_session` cookies are still being set by the SDK. This is a major bummer since if these cookies weren't set, it would allow me to comply with our local legal restrictions and implement the opt-in solution I've mentioned above.

My configuration:
```
{
  instrumentationKey,
  maxBatchInterval: 1000,
  disableCookiesUsage: true,
  cookieCfg: {
    enabled: false,
    setCookie: () => {
      throw new Error('?!')
    },
  },
  cookieMgrCfg: {
    enabled: false,
    setCookie: () => {
      throw new Error('?!')
    },
  },
  extensions: [this.reactPlugin],
  extensionConfig: {
    [this.reactPlugin.identifier]: {
      history: browserHistory,
    },
  },
}
```

**Comment by MSNev** [comment]
Hi @baxxos,

Well you have found 1 issue here in that the `cookieMgrCfg` is never used (this is a bug in the IConfig as it should also be `cookieCfg` -- will open a separate issue for that.

But once you set either the `disableCookiesUsage` to true or the `enabled` to false (on the cookieCfg) then there is ZERO way for this instance of the SDK to set (or get) any cookies (unless you use the `purge` function which always creates an expired cookie). Also once you provide a `setCookie` function that is the only way the SDK will set a cookie.

So if you are still getting an `ai_user` and / or `ai_session` getting created then I think you will probably find that there is another instance of the SDK getting injected into / onto you application / page. And that is the source of the cookies.

You should be able to debug this by using the browser F12 and set breakpoints in the @microsoft/applicationinsights-core-js `JavaScriptSDK/CookieMgr.ts` as this is the only places that cookies are created and read from the system.

And for reference on the purge note above you see [here](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCore/src/JavaScriptSDK/CookieMgr.ts#L217) that the purge implementation just checks if cookies are supported by the environment, as opposed to checking if they are ["allowed" (ie. enabled)](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCore/src/JavaScriptSDK/CookieMgr.ts#L140)

**Comment by baxxos** [comment]
@MSNev - thanks again for the reply, it seems that the `ai_user`/`ai_session` cookie pair in my browser was coming from the Browser Link (since I serve my local UI through ASP.NET backend running in Visual Studio).

I've tried deploying the application to a proper test environment and all cookie settings work as expected there!
