### ISSUE TITLE
[BUG] ApplicationInsights on an Aurelia Framework

### ISSUE THREAD

**Issue by asarang** [microsoft/ApplicationInsights-JS#1774]
Using the aurelia framework on our application deployed on Azure AKS. I have incorporated Application Insights and I am getting an error when trying to display the page. See the error below

![image](https://user-images.githubusercontent.com/440499/157872037-3d818d4d-2007-45ac-ab25-8f287c13a4ac.png)

The libray I am using is 

```
import { ApplicationInsights } from '@microsoft/applicationinsights-web'

const appInsights = new ApplicationInsights({
    config: {
      instrumentationKey: '<INSTR-KEY>'
    }
  });

```

**Comment by MSNev** [comment]
Based on the error message it looks like you are fetching the script `applicationinsights-web.js` from your own CDN and as part of that the mimetype (Content-Type) being returned for the script is `text/html` which the browser is blocking.

The CDN service / script should be returning `text/javascript` so that the browser will actually execute the script.

**Comment by MSNev** [comment]
It will be the server (or storage) that is serving up the files / CDN. So it will depend on what/how the files are stored and servered up.

For example from the js.monitor.azure.com perspective this is the CDN endpoint which has the default set for files ending with .js to be text/javascript, but for the source location of the files they also have additional meta-data which includes the Content-Type set as text/javascript.
