### ISSUE TITLE
customHeaders not available for "InternalApplicationInsightsEndpoint"

### ISSUE THREAD

**Issue by pmariani** [microsoft/ApplicationInsights-JS#1777]
Hi,
We are using Service Workers on Angular. I would like to by-pass service worker for application insights tracking calls. An easy way to do this is to specify the ngsw-bypass header for those requests.
I am setting this header via the `customHeaders` configuration variable, but the header is not included in the resulting call. 
After tracing the code, it seems to be due to https://github.com/microsoft/ApplicationInsights-JS/blob/master/channels/applicationinsights-channel-js/src/Sender.ts#L265 and `!isInternalApplicationInsightsEndpoint(_self._senderConfig.endpointUrl())` evaluating to false. 
Would there be issues in allowing "internal endpoints" to use custom headers?

**Comment by MSNev** [comment]
Yes, as if a customer header is included (sent) the browser will perform an OPTIONS call and when that header is not included in the response the browser will block the call from being sent.

**Comment by pmariani** [comment]
I see. I am working with servers which `AllowAnyHeader` and therefore include this one in their response, but I can see how the App Insights servers would be more tightly locked down. 
May I ask then:
- What is the purpose of the customHeaders configuration? I would assume this SDK would only communicate with the Application Insights systems and therefore it wouldn't be useful.
- Do you have a recommendation for configuring the SDK for usage with service worker?

**Comment by MSNev** [comment]
We actually have some customers that don't directly send the request to AzureMonitor, but rather send to themselves so they can either add more information or do some additional authentication etc. So the customHeaders allow them to populate / provide any additional headers they need.

In terms of running in a service worker environment, this is supported by the SDK. So (in theory) you shouldn't need to do anything special (some environments (react comes to mind) where you (previously) needed to provide a polyfill for XMLHttpRequest, but we now support using fetch(). I think the issue here is the addition of the `ngsw-bypass` header which is not "specifically" a service worker issue.

I think for what your trying to do (if I'm understanding correctly) is to use the `excludeRequestFromAutoTrackingPatterns` config option to specify the URL's you want to ignore. It's documented in the [README but the main automatic readme inclusion is truncating the description column, so here is a link to the file directly](https://github.com/microsoft/ApplicationInsights-JS/blob/master/README.md)

**Comment by pmariani** [comment]
Thank you for the background and details. 

What I am trying to do is actually a bit different. There are XHR requests which are tracked via App Insights tracking requests which is what I want. All requests (XHR and the AI ones) first go through the Service Worker by default, unless I set the magic header. I am able to do that for my XHR, but not for the AI requests. 

It's not a huge deal, but I thought I would ask. Thanks for your help.
