### ISSUE TITLE
Configure exact location of error boundary to be collected automatically when tracking an exception in azure app insights

### ISSUE THREAD

**Issue by pavinduLakshan** [microsoft/ApplicationInsights-JS#1835]
**Description/Screenshot**

I'm using Azure App Insights to track exceptions in a React app. As stated in the docs and some other tutorials, thrown exceptions are automatically collected by app insights React SDK, which is wonderful.

However, we want app insights to collect exactly in which error boundary a particular error occurred, but automatically reported error boundary exceptions don't have this information. This makes it hard to decode where exactly are errors in the production build.

Is there a way that allow us to define a custom property in error boundary via props which tells where this error boundary belongs to, and let app insights automatically pick it up when reporting the exception?

Thanks in advance.

**Environment**

 - OS/Browser: Mac OS Chrome
 - SDK Version [e.g. 22]: 3.3.1
 - How you initialized the SDK: Using the App Insights React SDK, as stated in docs

**Comment by pavinduLakshan** [comment]
bump

**Comment by pavinduLakshan** [comment]
@MSNev can you give me your thoughts on this issue?
Thanks

**Comment by MSNev** [comment]
Hey, sorry for the delay as I've been OOF.

My knowledge of React is low, but [looking at the code](https://github.com/microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-react-js/src/AppInsightsErrorBoundary.tsx#L21-L28) it appears that the ErrorInfo details are passed as additional properties to the trackException() call, so they should be available as part of the additional properties in the portal.

Another option is that you could use a telemetry initializer (see [addTelemetryInitializer()](https://github.com/microsoft/ApplicationInsights-JS#telemetry-initializers) ) to intercept the event before it's sent to move / set additional properties on the event to somewhere (a property) that you would like... 

Note: If you are using NPM packages, since v2.8.x the addTelemetryInitializer was moved to the Core, prior versions only enabled the usage of telemetry initializers when using the extensions/ applicationinsights-analytics-js plugin (which has always been included in the main AISKU)

**Comment by pavinduLakshan** [comment]
Thanks for replying.. 
Yes, AI sends the errorInfo, but in the production environment, these errors are in minified format and in order to convert it to unminified version
I solved this problem by getting the page title and inserting it to the exceptiondata packet in the telemetry initializer.
