### ISSUE TITLE
[BUG] CORS and Status Code 500 on /track requests

### ISSUE THREAD

**Issue by qubicaamf** [microsoft/ApplicationInsights-JS#1853]
In an unattended web application, that is supposed to be up and running for about a day, with a nightly automatic refresh, we are getting some strange errors.

The npm package installed is '@microsoft/applicationinsights-web' v2.8.3.
The connection method used is "Instrumentation Key", we tryied even the new "Connection String" method but the problem still.

After about 30m/1h of normal running and data collection, the 'https://dc.services.visualstudio.com/v2/track' endpoint stop working, giving a lot of CORS errors, accumulating a large buffer of logs (that will never be erased due to the request errors), causing memory leaks and bad performances on the web app.

We tryied to disable CORS, but the requests on '/track' are failing with Status Code 500...causing multiple track requests, all in pending...and again memory leaks and bad performance.

Attachments description:
 * The error stack:
   ![attach1-stacktrace](https://user-images.githubusercontent.com/32999837/173014631-4998de9e-ae45-4ce0-847c-f908a7db881a.png)
 * The error source (InstrumentHooks.js):
   ![attach2-jserror](https://user-images.githubusercontent.com/32999837/173014719-59b9360a-7146-41e8-8d81-6aa97c0560ed.png)
 * The failed request's body response (status code 500)
  ![attach3-stack](https://user-images.githubusercontent.com/32999837/173021321-8b9a6188-5fdf-488b-b08a-d2bdbcc19575.png)

**Comment by zakimaksyutov** [comment]
@qubicaamf, would it be possible to open a support ticket? To troubleshoot it we need application information such as instrumentation key.

**Comment by MSNev** [comment]
@qubicaamf Clarification question (as we are having internal discussions), Are you asking specifically about the 500's being returned or the issue with the backed up events (because the SDK is attempting to send them  -- it backs off the send requests as to not overwhelm the server, which will cause additional memory usage until the configured memory limits are reached)

**Comment by Nirmal1992** [comment]
Facing the similar issue :
![image](https://user-images.githubusercontent.com/17374745/186583309-2fc4423e-d7ce-4ac9-af13-99c530c8bdf5.png)

**Comment by MSNev** [comment]
Hi All, Guidance we have received from the server team on this issue is that this is because when the server has an issue and returns an internal error (5xx) error it doesn't respond with the CORS headers.  And as such this is a non-issue from their perspective.

The SDK (should) be seeing the 500 response and it should re-sending any included events as part of it's retry logic https://github.com/microsoft/ApplicationInsights-JS/blob/652c693abebc40ef58dbefe06bb93a948e4c9fa5/channels/applicationinsights-channel-js/src/Sender.ts#L930-L939
