### ISSUE TITLE
[BUG] AI (Internal): 18 message:"Failed to calculate the duration of the fetch call, monitoring data for this fetch call won't be sent" when call returns large list

### ISSUE THREAD

**Issue by msalaman** [microsoft/ApplicationInsights-JS#1855]
**Description/Screenshot**
When client successfully calls ARM to get subscriptions with a skip toke (call results in 200), the following exception appears in app insights:

e(a,t,r,n){ie(): AI (Internal): 18 message:"Failed to calculate the duration of the fetch call, monitoring data for this fetch call won't be sent." props:"{fetchDiagnosticsMessage:(url: 'https://management.azure.com/subscriptions?api-version=2016-06-01&%24skiptoken=[skip token is here, not sharing for security purposes]

This appears to only happen when large amount of subscriptions are returned (e.g. it's impacting someone who has ownership role on entire tenant).

**Steps to Reproduce**
Use app insights for client that makes a request that returns a large list, enable dependency fetching
 - OS/Browser: All broswers
 - SDK Version [e.g. 22]: 2.8.4

**Expected behavior**
App insights can fetch this dependency call without throwing exception

**Additional context**

**Comment by MSNev** [comment]
Do you have `enableAjaxPerfTracking` enabled?
This seems to indicate that a "real" exception occurred, can you try using either the [Chrome Debug Extension](https://github.com/microsoft/ApplicationInsights-JS/tree/master/tools/chrome-debug-extension) or the [Debug Plugin](https://github.com/microsoft/ApplicationInsights-JS/tree/master/extensions/applicationinsights-debugplugin-js) as both of these should expose the underlying error included with the logged internal.

Failing these 2 some additional steps to help track down whats going on would be to `enableDebugExceptions` which will cause a JS runtime exception at the point of the message being generated (it might get noisy in the F12 Dev tools) and it would probably be easier to not have the code minified. If using the CDN just remove the `.min` so it would be `ai.2.js` instead of `ai.2.min.js`
