### ISSUE TITLE
Effect of disabling cookies

### ISSUE THREAD

**Issue by unzld** [microsoft/ApplicationInsights-JS#1931]
Which app insights features/blades are affected when disabling cookies ? I tested and it seems that `session_Id`, `user_AuthenticatedId`, and `userAccountId` are still provided in the collected `pageView`s.

**Comment by MSNev** [comment]
When you disable cookie usage by the SDK this block all reading / writing of cookies for that instance.
So this blocks the following SDK (standard) cookies
- `ai_session`  (session_Id)
- `ai_user` (user_ Id)
- `ai_authUser` (user_AuthenticatedId, user_AccountId)

It also blocks any user accessing cookies (via the SDK helper functions), while it blocks the reading /creating / writing of these cookies the SDK still creates internal values for the `ai_session` and `ai_user` so they will still be reported as part of the event they just will (most likely) be a new value for every page request.

## Session Id

There is a fallback for the case of reading no value for the session id from the cookie, in that when the SDK unloads it will attempt to push the value into local storage. And during initialization if no cookie value is read it will attempt to read the session from local storage so that the session id is maintained (event without cookie support).

However, if there is no `ai_user` cookie (to link the same session) then the value stored in local storage is removed, as the session is "processed" before the user code, depending on your page you may still end up with a unique session for every request.

## User Id

Only ever read from the cookie (which when created has a lifetime of 1 year), so when blocked you generally get a new user id for each page load (SDK initialization).

## Auth User id / AccountId

Only ever read from the cookie. This value is only set from the existing cookie value or by the calling `setAuthenticatedUserContext(authenticatedUserId: string, accountId?: string, storeInCookie = false)` and passing the 3rd argument to `true`, if this function is not called then no value will be used. And yes the `accountId` is also stored in this cookie.
