### ISSUE TITLE
[BUG] Application Insights crashes Smart TV application after 15 minutes

### ISSUE THREAD

**Issue by JESUMH** [microsoft/ApplicationInsights-JS#1950]
**Description/Screenshot**
Recently I have performance problems with applicaciont insights. Application sends differents events using trackPageView() and trackEvent(). When we have deactivated application inshights analytics, apllication works properly.

**Steps to Reproduce**
1. Navigate between different pages.
2. Open video player
3. Send beat events and actions (play, pause and so on).

 - OS/Browser: WebOS LG Smart TV Chrome/53.0.2785.34
 - SDK Version [e.g. 22]: 2.7.4, 2.4.4
 - How you initialized the SDK:
```
    (<any>window).appInsights = new ApplicationInsights({
            config: {
              instrumentationKey: this._insightsId,
            }
      });
      (<any>window).appInsights.loadAppInsights();
```

**Expected behavior**
Prevent application crash or degradation services

**Additional context**
We haven't got any more information with debugger

**Comment by Karlie-777** [comment]
@JESUMH  so just to double confirm that is ApplicationInsights analytics plugin causing crashes of your website or just lowering your website performance? there are some configs that might help: 
 [enableDebugExceptions](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IConfiguration.ts#:~:text=enableDebugExceptions) [disablePageUnloadEvents](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IConfiguration.ts#:~:text=disablePageUnloadEvents) [disablePageShowEvents](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IConfiguration.ts#:~:text=disablePageShowEvents) [disableDbgExt](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IConfiguration.ts#:~:text=*/-,disableDbgExt,-%3F%3A%20boolean%3B)

**Comment by MSNev** [comment]
@JESUMH we would need some additional information to understand how / why this is occurring as we work really hard to avoid crashing any hosting application.

As you mentioned that this is a Smart TV, I will also assume that this is a low memory environment. As the SDK is targeted at web browsers the defaults are set based on the common environment. There are several optional [configuration options](https://github.com/Microsoft/ApplicationInsights-JS#configuration) that you could try adjusting to better support the low memory environment such as 
- `eventsLimitInMem` to reduce the number of batched events
- `maxBatchInterval` to change the amount of between sending batched events (defaults to 15 seconds `15000`)
- `isRetryDisabled` to drop events if the SDK can't talk to the endpoint (which could lead to an excessive number of events in memory because of multiple retries.
- `enableSessionStorageBuffer` While events are waiting for an acknowledgement they are also stored (by default) into session storage, if the SDK can't reach the endpoint the events will continue to be stored (and added) to session storage. If this is disabled it uses an in-memory array buffer (so events will be lost between restarts)

I'm not sure if any of these would "solve" the crashing (as it depends on what is causing the crash), as a JS SDK there should not be anything that we can directly do to crash a runtime, but memory exhaustion can have unexpected consequences.

**Comment by JESUMH** [comment]
@MSNev @Karlie-777 we enabled debug flag and we saw an error exception (max ajax call overflow). We tested the following app insights options (disableAjaxTracking: true and disableFetchTracking: true) and finally, apps works properly.

Thank you for your attention,
