### ISSUE TITLE
"Unminify" feature does not work if a "version" query string parameter is appended to the file path. - Manual upload

### ISSUE THREAD

**Issue by DevProLog** [microsoft/ApplicationInsights-JS#1952]
@mirkolugano: How is does working for you?

This is not working for me when using the manual upload feature:
I get the following error:
![image](https://user-images.githubusercontent.com/5717016/203973811-19bd1869-b213-43a2-872b-a3c691d5a035.png)

Call stack in Azure AI:
```
TypeError: Cannot read properties of null (reading 'focus')
at https:/<host>/js/ViewModels/consultatieViewModel.min.js?v=sMRxBC8wD7jFPv4DYXvirtjEaKewkEi7FKpvJUIcvsw:2:1468716
```

Source map filename:
```
consultatieViewModel.min.js.map
```

Content of source map file:
```
{"version":3,"file":"consultatieViewModel.min.js","mappings": ...
```

I could potentially change source map 'file' entry to
```
{"version":3,"file":"consultatieViewModel.min.js?v=sMRxBC8wD7jFPv4DYXvirtjEaKewkEi7FKpvJUIcvsw","mappings": ...
```

but I cannot rename the source map file name to
```
consultatieViewModel.min.js?v=sMRxBC8wD7jFPv4DYXvirtjEaKewkEi7FKpvJUIcvsw.map
```

since windows does not allow '?' in filename.

**Comment by DevProLog** [comment]
Referencing
https://github.com/microsoft/ApplicationInsights-JS/issues/1313

**Comment by Karlie-777** [comment]
@DevProLog it should allow '?' in file names since we only parse file name before question marks. I notice type error is `Cannot read properties of null (reading 'focus')
at https:/<host>/js/ViewModels/consultatieViewModel.min.js?v=sMRxBC8wD7jFPv4DYXvirtjEaKewkEi7FKpvJUIcvsw:2:1468716` so maybe it should be `https:/<host>/js/ViewModels/consultatieViewModel.min.js?v=sMRxBC8wD7jFPv4DYXvirtjEaKewkEi7FKpvJUIcvsw:2:1468716.`**map**`?

**Comment by DevProLog** [comment]
Yes, but it is simply impossible in windows to rename my map file to contain a '?'.
Windows does not allow special characters in file names.
