### ISSUE TITLE
[BUG] Global "JSON" and/or global "navigator" undefined during _parseResponse after silent refresh

### ISSUE THREAD

**Issue by sean-tillotson** [microsoft/ApplicationInsights-JS#1953]
**Description/Screenshot**
A) Stack trace thru IE11 
![image](https://user-images.githubusercontent.com/100216993/205795175-64765e3c-c130-40ab-ab9c-923b1a0256d3.png)

B) The slightly modified to fit our needs AI code block responsible for the error
![image](https://user-images.githubusercontent.com/100216993/205795878-a73e3d8f-b23a-48ca-8049-4290fb504223.png)

C) The unmodified root cause of the AI code responsible for the error
![image](https://user-images.githubusercontent.com/100216993/205796262-2650bd11-a892-4b3e-8ee0-d8a8d4915d66.png)

- the xhr.onreadystatechange triggers at readyState = 4 ( done, successful ) (this is the original trace error shown in (A))
- the `_parseResponse` method is triggered to read the response (shown above in (B))
- the `_parseResponse` method ends up triggering globally defined helpers `getJSON` and `hasJSON`
- `hasJSON` executes the code: `typeof JSON`, which throws an error if `JSON` itself is undefined, because the javascript `typeof` functions expects an `Object`.  Because these functions assume that the global JSON is always defined (which it always should be), there is no try/catch around it -- so the error does not bubble into AI's internal error handling, it throws the error uncaught and bubbles up to the hosting application. 

**Steps to Reproduce**
- Add applicationinsights-web NPM to a SPA, and initialize it with defaulted autocollection for telemetry.  
- In the SPA in an IE11 browser, trigger a reload of the application without refreshing the browser.
- The above step is not deterministic -- most times the `xhr.onreadystate` will bubble an error because global types are momentarily undefined, but not every time.  I suspect this has something to do with IE-specific nuances in refreshing a page.  

 - OS/Browser: IE11
 - SDK Version [e.g. 22]: 2.6.1 (also tried 2.8.9)
 - How you initialized the SDK:  NPM setup

**Expected behavior**
Any checks on presumed to be defined global types will never error, or will be caught and bubbled within AI code for the rare race conditions for users in unfriendly browsers.

**Additional context**
I'd be happy to create a PR with the expected try/catch blocks if that's helpful.  I know IE11 is not officially supported anymore, but there are multiple business reasons why people like me have to offer support to these users.  For what its worth, I think this error would be better reported to Microsoft IE11 team, but that is no longer maintained.  Also, I have seen other users on different occasions report this same non-deterministic error without being able to provide root cause -- so I know there are a few of us out here!

**Comment by MSNev** [comment]
For v2 we support IE8+ (but not IE7 "mode"), I think you will find that even though you are using IE11 it is running in IE7 mode (which doesn't define [JSON](https://caniuse.com/?search=JSON)) which is not supported (without you adding polyfills, this can also occur if you are using a "hosted" IE browser instance (.Net embedded IE WebBrowser v1) which will default to IE7 mode.

And we have a HARD requirement that [runtime support JSON](https://github.com/Microsoft/ApplicationInsights-JS#browser-must-support-json-class)

You can "request" that IE11 to run in a later mode by adding the `X-UA-Compatibility` tag 
https://learn.microsoft.com/en-us/openspecs/ie_standards/ms-iedoco/380e2488-f5eb-4457-a07a-0cb1b6e4b4b5
https://stackoverflow.com/questions/24572653/compatibility-mode-in-ie-11

**Comment by sean-tillotson** [comment]
We have the `X-UA-Compatibility` tag set to IE=edge.  The confusion for me is that it all works perfectly during app workflows, but it trips up during a very short-lived window during reload.

**Comment by MSNev** [comment]
HMM....

I've only seen this error when the global JSON is not available or 1 case where a polyfill was used but it didn't implement the full specification correctly (updating the JSON polyfill fixed that case).

The "TypeError: Object Expected" suggests to me that `return Boolean((typeof JSON === strObject && JSON) || getGlobalInst(strJSON) !== null);` is calling the `getGlobalInst` which means that JSON is not defined... Which is should not be...

Can you capture a fiddler trace of the "during app workflows, but it trips up during a very short-lived window during reload." as it sounds like for this sequence IE is not obeying your `X-UA-Compatibility` setting, or potentially there is a quick redirect page which will cause the "unload" (synchronous XHR request) to occur....

Another thought, based on your comment above about 2.6.1, can you try updating to the latest as we identified some IE8 breaks which where fixed, one of the issues was in a version of dynamicProto() -- so 2.8.9 should fully support IE8 again -- if this solves the issue then it could be one of the issues in dynamicProto() which was fixed in v1.1.6 (so perhaps checking which version is included in your package lock etc) and based on the release notes 2.6.1 was using v1.1.1 -- so maybe this is the underlying issue...
