### ISSUE TITLE
[BUG]ApplicationInsights still requires instrumentationKey

### ISSUE THREAD

**Issue by kkazala** [microsoft/ApplicationInsights-JS#1975]
`@microsoft/applicationinsights-web@2.8.9` still requires instrumentation key.
Even though property description for `connectionString` and `instrumentationKey` states: `Connection string of resource. Either this or instrumentationKey must be specified.`,  executing
```
         const appInsights = new ApplicationInsights({
                    config:{
                        connectionString: conn,
                        extensions: [reactPlugin],
                        extensionConfig: {
                            [reactPlugin.identifier]: { history: browserHistory }
                        }
                    }
                });
```
results in
```
Error: Please provide instrumentation key
    at throwError (HelperFuncs.js:623:1)
    at _self.<computed> (BaseCore.js:140:31)
    at Object.initialize (dynamicproto-js.js:265:1)
    at _self.<computed> [as initialize] (AppInsightsCore.js:22:38)
    at AppInsightsCore.dynProtoProxy [as initialize] (dynamicproto-js.js:374:1)
    at Initialization.js:172:1
    at doPerf (PerfManager.js:187:1)
    at _self.<computed> [as loadAppInsights] (Initialization.js:165:23)
    at Initialization.dynProtoProxy [as loadAppInsights] (dynamicproto-js.js:374:1)
```

**Comment by MSNev** [comment]
Yes, the connection string MUST still contain the valid instrumentation key. If not then you will get / see this error/message.

If you are attempting to mock and perform unit testing, so your don't populate your production data with your test data there are a couple of options. These are
- Use a dummy looking instrumentation key as the instrumentation key or in the connection string (so it passes validation but is not defined) eg. all zero's or something like that
- Use an obvious invalid key (we often use "testIKey"), and then ALSO set the `disableInstrumentationKeyValidation` config property to "disable" this check
- Just set the `disableInstrumentationKeyValidation` (should do the trick -- not tested this one recently)

Unless your are performing end-to-end testing (to see your data in the backend), you may also want to consider using a mocked transport (fake XHR / fetch etc) so that you tests don't need to create a network request.

**Comment by kkazala** [comment]
Hi Nev
I had whole connection string, including the instrumentation key.
The problem was occurring when instantiating AppInsights in my SPFx solution.
I just did a small demo to demonstrate it’s not working and… it’s working.
So it’s somewhere in my code, should be easy to fix it ;)
Sorry for taking your time 🙏
________________________________

**Comment by andrii-lundiak** [comment]
@kkazala no matter if `disableInstrumentationKeyValidation` is set or not I still have an error.
![image](https://github.com/microsoft/ApplicationInsights-JS/assets/85486996/2507ee9d-3877-4198-aca3-98b0b0fed9af)


Helps ONLY to set: ` instrumentationKey: ''` because actual code, EVEN from version https://www.npmjs.com/package/@microsoft/applicationinsights-web/v/3.0.5-nightly3.2310-08 still looks like ignore.

My whole setup:

```
this.appInsights = new ApplicationInsights({
      config: {
        // instrumentationKey: '', // temp fix until `@microsoft/applicationinsights-web` will change the API code.
        connectionString: instrumentationKey,
        enableAutoRouteTracking: true,
        disableTelemetry: instrumentationKey === '',
        disableInstrumentationKeyValidation: true
      }
});
```
Note. If `disableTelemetry` is false or undefined the error still occur.
 
Would it be the explanation to reopen this issue?

**Comment by andrii-lundiak** [comment]
UPD. And I also did have my code problem.

I ended up with such code:

```
const connectionString = this.configService.config.appInsights || '';
    const instrumentationPart = connectionString.split(';')[0];
    const instrumentationKey = instrumentationPart.split('=')[1];

    this.appInsights = new ApplicationInsights({
      config: {
        instrumentationKey,
        connectionString,
        enableAutoRouteTracking: true,
        disableTelemetry: instrumentationKey === '',
        // disableInstrumentationKeyValidation: true // doesn't work  - doesn't influence
      }
    });
```

If anywone does have better way how to setup so that I wasn't blocked by AppInights please let me know.

**Comment by MSNev** [comment]
Note: You can't just pass the instrumentation key as the "connectionString" the connectionString MUST specify the placeholder with the instrumentationKey so 

`connectionString: "instrumentationKey=xxxxx"` you can also specify an "empty" value `connectionString: "instrumentationKey="`. In both cases if the value of the instrumention key is not "valid" then you will still need to specify the `disableInstrumentationKeyValidation: true` to stop the originally reported warning.

**Comment by andrii-lundiak** [comment]
@MSNev Yes, I now and I tried to set `instrumentationKey=` but then My Frontend code still was sending AppInsgights requests. And I intended to disable it.

**Comment by MSNev** [comment]
Understand, I think what you want for this case (which you are doing) is to set the `disableTelemetry` and as long as the connectionString contains the "empty" `instrumentationKey=` entry then then presence of the `instrumentationKey` in the root of the config is not necessary (for the SKU) as internally when a `connectionString` is present and it contains an `instrumentationkey` (we lowercase all keys as part of parsing the connection string) then we actualy overwrite any previously provided `instrumentationKey` [the code for this is here)[https://github.com/microsoft/ApplicationInsights-JS/blob/03986050487a342f07e981469bc159567a4c70ba/AISKU/src/AISku.ts#L196-L201].

Now (if) your using the AppInsightsCore class directly then none of the above is true and you do need to provide as the core doesn't call the `parseConnectionString` with any provided connection string.

And the `disableInstrumentationKeyValidation` is only stopping the "validation" of any provided `instrumentationKey` it does NOT stop the "check" for whether one was present (there is NO configuration to stop that check), and we have no plans to "add one.

Recommendation, would be
- mostly the same to what you already have (except including an "empty" key) in the connection string
- Include an "valid" looking instrumentationKey (like all zeros `0000...0000` etc) and then check for that string to also set the `disableTelemetry`
- Include a complexly invalid instrumentationKey in the connection string (maybe something like `InstrumentationKey=DisableTelemetry`) and then "set" the `disableTelemetry` to `true` if that string value is present in the connection string (this WILL also need the `disableInstrumentationKeyValidation` set to true, but you can actually always include that one even for production as it just stops the "validation" check of the provided key)

And there are probably a few other options (including what you have already).
include

**Comment by alsmyr** [comment]
> hi there so if site disclosed their “APPINSIGHTS_INSTRUMENTATIONKEY” in page source code means sensitive information is leaked ????????

Only if you consider that key sensitive information. I am not and neither are most other people.
