### ISSUE TITLE
Missing traceparent header when running multiple SDK instances

### ISSUE THREAD

**Issue by stypich** [microsoft/ApplicationInsights-JS#2120]
I am having trouble with properly configuring Application Insights in my Angular web app and getting proper data logged.

I have configured the SDK to log dependencies with W3C tracing like this:
```
    this.appInsights = new ApplicationInsights({
      config: {
        instrumentationKey: 'XXXXXXXXXXXXXXXXXXXXXX',
        enableAutoRouteTracking: false, // set to true to get a new operation id per page view.
        distributedTracingMode: DistributedTracingModes.W3C, // option to enable W3C distributed tracing
        enableCorsCorrelation: true, // option to enable "traceparent" header in outgoing requests
        correlationHeaderDomains: ['api.at.completely.different.domain.com'], //option to whitelist domains for "traceparent" header inclusion
        namePrefix: "myAppInsights",
        disableAjaxTracking: false, //just to make sure
        maxAjaxCallsPerView: -1,
        maxMessageLimit: 500
      }
    });
    this.appInsights?.loadAppInsights();
    (window as any).myAppInsights= this.appInsights;
```
I am relying on autocollect of the dependecy data and when I run my app in `localhost`, the dependency calls contain traceparent header and I can correlate all calls in my App Insights as well in App Insights of the dependency API. All works as it should.
 
When my application is deployed to TST or PROD, it is loaded by yet another web app that has its own Application Insights instance. That instance is an older version of the SDK that lacks traceparent implementation and will not be upgraded.

In dev tools console I can see both SDK instances properly configured.

I am struggling with several issues:
1. When deployed to TST or PROD, dependency calls do not contain traceparent header any more. I have repeatedly verified and confirmed this by looking at the requests in dev tools. I tried to use the snippet, but I could not get it to work. What do I need to do to enable the header?
2. I am using Telemetry Viewer extension for my browser and in its log I see that when deployed to TST or PROD, my SDK instance logs only "Fetch" dependencies, but does not log "Ajax" dependencies, whereas the other SDK instance logs both of those fine. The calls that are not being logged are the calls that are made to the domain listed in `correlationHeaderDomains` config option. All these calls are `HTTP 200` by the way. What do I need to do to collect the Ajax dependency calls as well?
3. In Telemetry Viewer logs I see hundreds of "component-timing" events sent to the endpoint by my SDK instance but all of them contain measurement "elapsed: NaN". What do I need to do to stop sending those?
4. I get bunch of exceptions logged in my Application Insights in Azure with message: `"message":"Uncaught [object Object]: {\"messageId\":26,\"message\":\"AI (Internal): 26 message:\\\"Failed to send telemetry.\\\" props:\\\"{message:partial success 1 of 6}\\\"\"}","typeName":"String"}` I suspect that these exceptions are logged due to "component-timing" mentioned above.

Two most important issues for me are traceparent header and logging of the dependency calls into my Azure App Insights.
I would really appreciate any guidance on how to resolve them.

**Comment by MSNev** [comment]
Which versions are you loading.

I suspect the issue is that the 2nd version being loaded is overwriting the first version loaded and thus causing multiple exceptions and may also be causing the SDK (v2 or v3) to fail to get initialized.

By default the current v2 and v3 automatically have W3C tracing enabled so if initialized and hooked it will be sent. It's possible that something is also either
- Replacing the hooked version of `fetch` and `XMLHttpRequest` - which would cause the v2 and v3 to fail to intercept the calls
- The code has pre-cached the global `fetch` instance before we have patched it and thus any usage would be bypassing the patch.
- etc

How are the SDK's loaded? 
- From the CDN?

For the latest version if you consume via `npm` you can wrap the SDK into your own bundles which don't rely on the global `appInsights` and the global namespace `Microsoft.ApplicationInsights`

For the following `distributedTracingMode: DistributedTracingModes.W3C, // option to enable W3C distributed tracing` if `DistributedTracingModes` is not a "defined" object during JS runtime (when loading from the CDN it will be namespaced as `Microsoft.ApplicationInsights.DistributedTracingModes.W3C` so this could cause a JS error and result in the Sdk failing to be initialized. But as mentioned above you can remove this with the latest versions.

Additionally, starting with the "next" release we will be causing v2 of the SDK to expose itself as both `Microsoft.ApplicationInsights` and `Microsoft.ApplicationInsights2` where the second namespace will never be corrupted by an earlier or later version (1 or 3) of the SDK. Version 3.x (which is not yet available from the CDN as ai.3.min.js) already publishes itself as `Microsoft.ApplicationInsights` and `Microsoft.ApplicationInsights3` but if the former is already present it also won't overwrite existing namespaces (while v2 will always overwrite `Microsoft.ApplicationInsights)

**Comment by MSNev** [comment]
We are still working on finalization the documentation around the new multiple "namespaces" and how they will work and how you can avoid issues with multiple versions being loaded from the CDN.

**Comment by MSNev** [comment]
Hmm, I've just spent some time looking over the old v1 code and at first glance it looked like it would work, however, as all versions of AI use the same set of internal "flags" for tracking I think the v1 is corrupting the code that v2 and v3 is looking at...

v2/v3 support multiple instances but all of v1 doesn't....

What is the component using 1.0.20? Do you know if they accepting contributions as 1.0.22 is the latest v1 (but would still have the same issue)

**Comment by stypich** [comment]
They load the `ai.min.js` in the `<head></head>` and then in the `<body></body` they have a script that configures their SDK as a bundle for Require and then the `require` calls the `init()` of the bundle.

Then they load my app that uses npm package.

So, they load and initialize before my SDK instance, and if indeed v1 does not support multiple instances, then yeah, we could have a problem. I doubt that upgrade to 1.0.22 would make any sense, I guess it would be better to insist on an upgrade to v2 or v3.

It seems that I am stuck at this moment unless upgrade is made.

Is there anything else that I might be missing or not thinking about that could help me here?

Again, thank you for your help.

**Comment by MSNev** [comment]
So I assume that they are hosting their own copy of `ai.min.js` as v1 is published as `ai.0.js`

>  I guess it would be better to insist on an upgrade to v2 or v3.

This would be good and v2 does have a path to "easily" support this (if they are not heavily using the v1 API), by just using the v1 version of the snippet (which provides a shimming layer) v3 does not support this shimming layer, so that would only work if they are NOT using the v1 API and only using the automatic support...

> Then they load my app that uses npm package.

Yeah, this makes sense why your ajax requests get lost as v1 will (very simplistically) be setting the "done" flag which would then stop v2/3 from doing anything else.... We (might) be able to break this global overriding (technically it's the "xhrData" object thats added to the XMLHttpRequest instance) by versioning into this instance... Would need to try this out... If that works then updating v2/3 might avoid this specific issue.

**Comment by MSNev** [comment]
While "technically" we don't "support" using v1 with v2/3, this (might) be something we can work around -- but there are other complications that I need to followup (ie. any other existing code that "expects" the `xhrData` to always be present and called that) getting them to update would be a better option

**Comment by MSNev** [comment]
@stypich As part of investigating possible options / workarounds for this we have uncovered another potential issue which cause a larger problem (by fixing this issue) so while we are still investigating, it may take longer than expected to address this concern.

In the meantime, is it possible to get the hosting framework to "set" the `disableAjaxTracking` config option for their instance to `true` as this would avoid v1 from instrumenting the XHR and causing this issue... It will also mean that they will stop getting any  dependency telemetry...

**Comment by stypich** [comment]
Thank you for the research and these options/workarounds.

In light of v1 limitations clearly spelled out in this thread I am trying to make a case for SDK upgrade to at least v2 or using the workarounds. I will keep you up to date so that you don't spend your valuable time on chasing old code.

Thank you so much!

**Comment by MSNev** [comment]
Update:
Ok, I've just pushed in some major changes to v2 and v3 to try and better segregate the problem caused by v1 interactions, however, there are some potential issues that might cause problems with using multiple versions of v2 / v3 in the same environment like
- Having "multiple" values (headers) for some keys (like traceparent and Request-Id)

To work around the potential of creating "invalid" (unhandled) `traceparent` header values (because there are multiple or they include comma separated values (default for multiple values), both versions of the SDK will only attempt to "set"  the `traceparent` header if it has detected that it has NOT already been set either by another SDK instance or by the application.

This does mean that while there will always be a "valid" `traceparent` header, it may NOT always be your expected instances (because another instance has set it). The only solution around this is to have the multiple SDK instances coordinate and only attempt to set the `traceparent` header for the Ajax (XHR - fetch already handled this) requests that they are interested in, via config that is only available in v2 and v3.

**Comment by MSNev** [comment]
v2.x is now published to `npm`
v3.x is still in progress

**Comment by tomasszabo** [comment]
FYI - I had the same problem with simple static web page loading App Insights JS using snippet (e.g. `!function (v, y, T) { var S = v.location, k = "script", D = "instrumentationKey", C = "ingestionendpoint"...`) and the web app was deployed on app service where `APPLICATIONINSIGHTS_CONNECTION_STRING` was defined. After I removed environment variable from app settings, it started to send the correlation request headers.

**Comment by MSNev** [comment]
v2.8.16 has now been promoted as the primary version which contains a "work-around" for this issue.
Basically, this will now allow the "first" SDK instance to "set" the `traceparent` header, rather than using a "global" flag to address all headers.

However, it does mean that if there are multiple SDK instances who "set" the header (and it's not your primary instance) then there needs to be some co-ordination between the SDK instances so they only try and instrument their own Ajax requests.

**Comment by MSNev** [comment]
Fully released for v2.x
Update labels to reflect that this is now waiting for v3.0.3 to be released and deployed.

**Comment by MSNev** [comment]
> FYI - I had the same problem with simple static web page loading App Insights JS using snippet (e.g. `!function (v, y, T) { var S = v.location, k = "script", D = "instrumentationKey", C = "ingestionendpoint"...`) and the web app was deployed on app service where `APPLICATIONINSIGHTS_CONNECTION_STRING` was defined. After I removed environment variable from app settings, it started to send the correlation request headers.

Sorry just re-read your response, this would have been because you are loading the SDK via the snippet AND with the environment string the deployment was also loading (and initializing the SDK). By removing the environment variable the "automatic" version fails to initialize which then avoids the "multiple" SDK issue.

I believe that there is also an additional "switch" somewhere (@Karlie-777 ) to disable the automatic injection??

**Comment by Karlie-777** [comment]
@MSNev it seems that should set initialize to false? https://github.com/microsoft/ApplicationInsights-JS/blob/4eabbbbe26e73a1bfe270007ae10af9658bad489/tools/applicationinsights-web-snippet/src/snippet.ts#L39

**Comment by MSNev** [comment]
No, I believe that we want the snippet to always initialize the SDK once it downloads... It should be that the auto-injection should not attempt to include the "auto-inject" snippet when
- There is no configuration
- It detects that there is already a snippet (script tag) on the page or it's explicitly including the SDK (I believe I worked with Hector on this portion quite a few years ago for node)

This is also v7 (not yet released), but v6 (the current) should be the same.

**Comment by tomasszabo** [comment]
When I removed `APPLICATIONINSIGHTS_CONNECTION_STRING` then there was only 1 SDK loaded by the snippet and it has worked as expected. 

What I wanted to bring into light is the fact, that the situation, when using 2 App Insights SDKs at the same time, may not be so rare as one may think, because App Services may have some back-end code where App Insights with auto instrumentation is needed and a web page with App Insights snippet at the same time. And there is no option to turn off auto instrumentation only for web page, it will turn it off for whole App Service. Therefore, I think, App Insights Javascript SDK needs to handle this situation in some standardized way.

**Comment by MSNev** [comment]
> And there is no option to turn off auto instrumentation only for web page,

Hmm, agree, there needs and I thought there was...
