### ISSUE TITLE
[BUG] stopTrackEvent requires property values to be strings

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/ApplicationInsights-JS#2209]
**Description/Screenshot**
The README says that `properties` accepts _any type_: https://github.com/microsoft/ApplicationInsights-JS/blob/HEAD/README.md#sending-telemetry-to-the-azure-portal
However, `stopTrackEvent` is typed to only accept a `{ [key: string]: string }` which is in direct contradiction with the above.

**Steps to Reproduce**

 - OS/Browser: Edge
 - SDK Version [e.g. 22]:
 - How you initialized the SDK: npm

**Expected behavior**
I can include anything I want in properties.

**Additional context**
Version 3.0.5.

**Comment by siyuniu-ms** [comment]
Hi @50Wliu Based on my local test, the following call was successful:
```
appInsights.startTrackEvent("test99"); 
appInsights.stopTrackEvent("test99", {"a":3.14, b:"TEST",c:{apple:"banana"}, d:80000})
```
I have verified in my Azure portal, and the telemetry appears as expected.
<img width="379" alt="image" src="https://github.com/microsoft/ApplicationInsights-JS/assets/123212536/36b9e0bf-15bd-4c98-af08-9764fee64b75">

We will update the README accordingly to include this example. The current one may cause confusion as it contains "properties: {}".

Your feedback is greatly appreciated. If there are any edge cases or further suggestions, please let us know.

**Comment by 50Wliu** [comment]
Hi @siyuniu-ms, thanks for looking into this. I'm referring to the TypeScript types which seem to be incorrect in this case.
See: https://github.com/microsoft/ApplicationInsights-JS/blob/6365dad8fc96be1e0ee8008b3f6dd2748aa2e107/AISKU/src/AISku.ts#L668

**Comment by siyuniu-ms** [comment]
> Hi @siyuniu-ms, thanks for looking into this. I'm referring to the TypeScript types which seem to be incorrect in this case. See:
> 
> https://github.com/microsoft/ApplicationInsights-JS/blob/6365dad8fc96be1e0ee8008b3f6dd2748aa2e107/AISKU/src/AISku.ts#L668

You are corret. This behavior is intentional. As you may have observed in the Azure portal, telemetry data is organized into two distinct tables: one for measurements and another for properties. When our telemetry is transmitted to Azure, we ensure that the fields are segregated based on their data types — numeric values are categorized as measurements, while strings and nested objects are categorized as properties.

While the current functionality has been validated through local testing, we acknowledge the importance of providing clarity on this process and ensuring consistency between different track function. As such, we plan to incorporate additional documentation and ensure consistency of converting customer properties.

**Comment by siyuniu-ms** [comment]
PS example in #2268 may help for better understanding

**Comment by 50Wliu** [comment]
Thanks, but I'm still confused. I understand that numbers, nested objects, etc. can be transmitted, but my point is that the typings in this repo forbid that. In #2268 one of your examples is `appInsights.stopTrackEvent("test",{property: {p1:3, p2:4}})`.

If I try this, I get the following TypeScript error:
![image](https://github.com/microsoft/ApplicationInsights-JS/assets/2766036/7f9692c0-40d8-4e0d-a2c7-eed84153a670)

**Comment by siyuniu-ms** [comment]
interesting, I could run it on my side: 
<img width="896" alt="image" src="https://github.com/microsoft/ApplicationInsights-JS/assets/123212536/ff742a8b-db3b-4d9b-a384-e67dc764764e">
****
I also have a test on edge Version 121 using 3.0.5 version loaded from script and it works.

Could you provide a more detailed screenshot and also try to print out Microsoft.ApplicationInsights.__ms$mod__ in dev tool?

**Comment by siyuniu-ms** [comment]
Got it. Since this issue doesn't impact the functionality directly, we'll classify it as an "improvement" and address it in line with our plan to ensure consistency in converting customer properties, as mentioned earlier. If it were to affect users' ability to send out telemetry, we'd prioritize an immediate fix before the next release. Just double check, could you get the telemetry when calling appInsights.stopTrackEvent("test", { property: { p1: 3, p2: 4 } }) currently?
