### ISSUE TITLE
https://dc.services.visualstudio.com/v2/track returning 400 bad request in case of log out

### ISSUE THREAD

**Issue by kulabanta** [microsoft/ApplicationInsights-JS#2215]
When we try to log out from our web application or refresh the page ,lots of ping calls are getting called for url https://dc.services.visualstudio.com/v2/track and all calls  are returning 400(not incase of refresh).
It is slowing down the logout process and browser is undergoing to a state of freeze.

It is only happening in the latest version 3.0.5 .

![issue](https://github.com/microsoft/ApplicationInsights-JS/assets/64955273/7e6e0633-a73f-4625-b0ce-b14dcdf4ab18)

**Comment by MSNev** [comment]
We released v3.0.6 to npm yesterday to address an issue introduce in v3.0.4 which causes this issue to occur.
And we promoting v3.0.6 as the primary version (available via the CDN with `ai.3.min.js` and `ai.3.gbl.min.js`) on Monday

v3.0.6 is a targeted fix for this specific issue https://github.com/microsoft/ApplicationInsights-JS/milestone/90

**Comment by MSNev** [comment]
For reference, this issue is triggered only when the browser is unable to send all events that are "batched" (in-memory) when the page is "unloading" (Navigating to another page, closing the browser or switching to another tab).

This generally, means that the "amount" of batched events exceeds the `sendBeacon()`

**Comment by MSNev** [comment]
Not sure exactly "why" it's returning a `400` though, perhaps because too many events have being "sent".

Can you try using v3.0.6?
- If you using `npm` then just consume the latest package.
- If your using the CDN (snippet) then you can change the `src` to be `ai.3.0.6.gbl.min.js` or `ai.3.0.6.min.js` (at least until Monday (PST) when we promote this version to be the primary version.
