### ISSUE TITLE
[BUG] Initialization exception after upgrading from 2.7.1 to 3.2.1

### ISSUE THREAD

**Issue by m0glan** [microsoft/ApplicationInsights-JS#2349]
**Description/Screenshot**

Cannot read properties of undefined (reading 'length')
    at __spreadArrayFn

![image](https://github.com/microsoft/ApplicationInsights-JS/assets/12647829/dc337159-b459-4af1-aa6f-01f2c5e66f02)

**Steps to Reproduce**

 - Framework: EmberJS 5.4
 - OS/Browser: Windows 11/Edge
 - SDK Version [e.g. 22]: 3.2.1
 - How you initialized the SDK:

```js
import { ApplicationInsights } from "@microsoft/applicationinsights-web";

export function initialize(appInstance) {
  const appInsights = new ApplicationInsights({
    config: {
      connectionString: [redacted],
      autoTrackPageVisitTime: true,
      enableAutoRouteTracking: true,
      enableCorsCorrelation: true
    },
  });
  appInsights.loadAppInsights();
  const service = appInstance.lookup("service:analytics")
  service.subscribe((name, properties) => {
    appInsights.trackEvent({name, properties});
  });
}

export default {
  name: "analytics",
  initialize,
};
```

**Expected behavior**

It was working fine before the upgrade and there seem to be no changes in initialization with the new major version.

**Comment by MSNev** [comment]
Drilling into the generated code for v3.2.1, it appears that this issue is occurring in the `AppInsightsCore` at this point in the code

`_configExtensions[_DYN_PUSH /* @min:%2epush */].apply(_configExtensions, __spreadArray(__spreadArray([], extensions, false), cfgExtensions, false));`

Where the `__spreadArrayFn` is defined as
```js
export function __spreadArrayFn(to, from) {
    for (var i = 0, il = from.length, j = to.length; i < il; i++, j++) {
        to[j] = from[i];
    }
    return to;
}
```

So the above is the generated code from
```ts
                let cfgExtensions = config.extensions;

                // Extension validation
                _configExtensions = [];
                _configExtensions.push(...extensions, ...cfgExtensions);
```

So it appears that in this case the `cfgExtensions` is `undefined` and the `__spreadArrayFn` is not handling this and the `from.length` is causing this issue. 😦 

However, we always populate the "extensions" with an empty array based on our dynamic configurations... So perhaps there is something going on here with the Ember runtime that is blocking our ability to assign the empty extension (which we do indirectly via `Object.defineProperty`)

If this hypothesis is correct, you "might" be able to add the "extensions" to the config you are passing in, or if you assign your config to local variable (not as a `const` but as a `let`) then either of these (might) allow the runtime to "update" and process the passed config object.  <- guessing

So


```ts
const appInsights = new ApplicationInsights({
    config: {
      connectionString: [redacted],
      autoTrackPageVisitTime: true,
      enableAutoRouteTracking: true,
      enableCorsCorrelation: true
      extensions: []
    },
  });
```

If the runtime is treating and freezing the passed config, the above might still fail (but with a different error)

so you could try

```ts
let theConfig = {
    config: {
      connectionString: [redacted],
      autoTrackPageVisitTime: true,
      enableAutoRouteTracking: true,
      enableCorsCorrelation: true
    },
  };

const appInsights = new ApplicationInsights(theConfig);
```
This will explicitly tell the runtime that the "config" is not a constant.

or 

```ts
let theConfig = {
    config: {
      connectionString: [redacted],
      autoTrackPageVisitTime: true,
      enableAutoRouteTracking: true,
      enableCorsCorrelation: true,
      extensions: []
    },
  };

const appInsights = new ApplicationInsights(theConfig);
```
