### ISSUE TITLE
Examples of usage in Angular 2

### ISSUE THREAD

**Issue by johnkattenhorn** [Microsoft/ApplicationInsights-JS#387]
I've been searching for some guidance on the best way to integrate within an Angular 2 App. Is there any document or posts / snippets available that might get me started ?

**Comment by MarkPieszak** [comment]
Spoke with @johnkattenhorn about this one, currently creating an Angular (2+) Module for this here: https://github.com/MarkPieszak/angular-application-insights

@kamilszostak @Dmitry-Matveev Biggest concern is that the SDK isn't setup currently to be isomorphic/universal friendly, so when running in an environment where an Application is serialized on the server, we want the entire SDK to basically not get created.  We basically just need a test to see if `window` even exists, if not, just create either an empty version of the SDK with all `void` returns, or not set it to the window at all. 
Any guidance on that, or where I can help put in a PR to patch this, would be great!

**Comment by KamilSzostak** [comment]
@MarkPieszak could you share a sample project to demonstrates this scenario?

**Comment by MarkPieszak** [comment]
@KamilSzostak Apologies on the late response!
I could make a quick branch if that'll help.

So I finally had some time to fix the issue (as a few people were running into this, that were using application-insights with JavaScriptServices or my sister repo).

When using the library in a server-rendered scenario (ie: angular universal), even when you conditionally wrap the code to make sure it only is ran in an `isPlatformBrowser()` scenario, the `get appInsightsInstance` is still packaged into the server bundle, and errors out due to no window test.

The error happens here: https://github.com/Microsoft/ApplicationInsights-JS/blob/a19453442719edc4516548f63699ea218018ba0c/JavaScript/JavaScriptSDK.Module/AppInsightsModule.ts#L95

It's actually as easy as added a quick `if()` statement to return whenever window doesn't exist, and everything works! :)

Any idea when we can get this PR through so everyone can take advantage of this?
https://github.com/Microsoft/ApplicationInsights-JS/pull/486
