### ISSUE TITLE
Clarfication of issues fixed in Version 1.0.9 

### ISSUE THREAD

**Issue by shkrishms** [Microsoft/ApplicationInsights-JS#418]
There are a couple of things I am blocked on right now with ApplicationInsights. It looks like these issues are due to existing bugs and they will be resolved in 1.0.9 (https://github.com/Microsoft/ApplicationInsights-JS/milestone/24)
Nevertheless, I want to validate the above understanding so that I can be clear if I need to fix things on my side or these are bugs and just wait for the next release.

1.	Correlating client to server requests:
My client is sending logs to application insight resource X and my server is sending to resource Y. I understand that to correlate requests from client to server (traces in X an Y have common operation is), you need to set DisableCorrelationHeaders = false.
But doing the above does not set the required headers (ms-root-id) in my client dependency calls. I am trying with chrome.

Is this a bug that will be fixed in 1.0.9? If not what am I missing?

2.	Browser exceptions are not tracked. Again trying on chrome.

              Is this a bug that will be fixed in 1.0.9?If not what I am missing?

Please let me know if my understanding is correct. Also, do you know when 1.0.9 will be released?

**Comment by KamilSzostak** [comment]
1) Page view to dependency calls correlation only works for requests within the same domain. So if your page is making AJAX calls to a different domain they won't have the `ms-root-id` header and won't be correlated. 
We are planning to enable the correlation feature by default as part of 1.0.9 release. 
2) Yes, #282 will be fixed in 1.0.9

We don't have a fixed data for 1.0.9 release. I hope to release it next week. The release schedule is available [here](https://github.com/Microsoft/ApplicationInsights-Home/wiki/SDK-Release-Schedule), I'll update it as soon as I know the release data.

**Comment by shkrishms** [comment]
Thanks Kamil.
How to correlate request across domains? Should we just include the headers manually?

**Comment by KamilSzostak** [comment]
Yes, you can include `ms-root-*` headers manually using a [telemetry processor](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#addtelemetryinitializer).
