### ISSUE TITLE
Host JS snippet at the ASPNET CDN

### ISSUE THREAD

**Issue by AKachan0v** [microsoft/ApplicationInsights-JS#420]
Hi guys,

we are using of AI for clients side telemetry and the domain which hosts the JS snippet looks a little suspicious ("https://az416426.vo.msecnd.net/scripts/a/ai.0.js"). Every time when I configure our security header I'm worry that the script can be removed to some other place, because this one doesn't look to be very solid.

Can you please put it for ASPNET CDN (for example):
- it will makes things much easier when we configure security headers (ASPNET CDN is allowed in the most case);
- also there can be bonus in performance on loading (not sure that it is very important since in most case it will be cached on client side);

**Comment by KamilSzostak** [comment]
I'm aware that this URL may not look like it's the official one, but it is 😃.  And since it's referenced in the snippet and most of our customers are using it, it's hard to change it and we have to support it. 

Regarding *2 - the URL is pointing to Azure CDN which helps to distribute the script fast. So the performance gain from using the ASPNET CDN will be minimal. Most probably you can save one DNS call if you're loading other scripts from ASPNET CDN. 

We will consider uploading the `ai.0.js` file to ASPNET CDN and changing the snippet code. But even after that, we will have to support both locations because we cannot guarantee that all users will update to the latest snippet.

**Comment by MSNev** [comment]
Tagging as "fixed" waiting release even though strictly speaking the snippet can be used as is from the readme
This is more for release tracking when we go to create the release notes.

**Comment by MSNev** [comment]
CDN Deployment rolled back due to #1452

**Comment by MSNev** [comment]
Re-closing now that 2.5.11 is fully released
