### ISSUE TITLE
Events duplication when trying to track URL click

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-JS#436]
Reported by customer - when trying to track the usage of URL clicks - some events got duplicated in Analytics.

Code example with the details stripped out:

```
<div class="bar-simples">
  <div>
    <a onclick="appInsights.trackEvent('eventName', {URL: '/some/service/url.aspx', Number: '1'});" href="/some/service/url.aspx" class="bar-simples-link">Name of the link</a>
  </div>
</div>
```

cc: @NumberByColors, @acearun

**Comment by biosis21** [comment]
I have the same issue
![5](https://user-images.githubusercontent.com/6310176/35462510-e73f431e-02f4-11e8-8d3a-8227945fb3a1.png)
When will be your next release? Can I expect this in it?

**Comment by aaron-mciver** [comment]
Having the same issue on 1.0.20 @KamilSzostak; two events which were both captured in Application Insights however only one event was sent. We've also compared this to another log aggregator we make use of and send to in parallel which only has one instance of the event versus two. Polling a days worth of events, we had ~800 for a specific action we were tracking and of those 6 were duplicated. This becomes problematic as we are keying off these events to identify specific actions that were taken. While we can certainly deduplicate the event data, the concern is that we also may be missing data unless we _know_ what is causing the duplication however haven't had the bandwidth to address as of yet?

_2018-09-18T01:10:39.042Z Add/Update Proxy Bid	customEvent	{"Category":"buyonic","AppVersion":"buyonic - 1.3.14117","PreferredICPriority":"32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000","ExternalAccountKey":"5200714","ChosenICLocation":"Transport Drive I.C.","ImpersonatedBy":"","PreferredIC":"Atlanta Stockbridge I.C.,Birmingham I.C.,Blue Mound I.C.,Chicago I.C.,Clearwater I.C.,Cleveland I.C.,Columbus I.C.,Delanco I.C.,Denver I.C.,Detroit I.C.,Fontana I.C.,Foster Road I.C.,Fremont I.C.,Ft. Worth I.C,Highland I.C.,Houston Kuykendahl I.C.,Kansas City I.C.,Memphis I.C.,Mobile I.C.,Montclair I.C.,Nashville I.C.,Orlando I.C.,Philadelphia I.C,Phoenix I.C.,Pittsburgh I.C.,Redbird I.C.,Shadeland I.C.,Transport Drive I.C.,West Palm Beach I.C.,Wyoming I.C.","EventValue":"undefined","EmployeeId":"00000","BidAmount":"00000","BidMethod":"Proxy","SaleDate":"09-19-2018","PageName":"Preview 9/19/2018","Platform":"Android","IDNumber":",,,,,,,,,,,,,,,,,,,,,,,,,,,,,","Email":"N/A","Auction":"ADESA PA","Action":"Add/Update Proxy Bid","House":"ADESA","Label":"bid","Page":"file:///android_asset/www/index.html#","Size":"MEDIUM","Vin":"1N4AL3AP8FC182178"}_


_2018-09-18T01:10:39.042Z Add/Update Proxy Bid	customEvent	{"Category":"buyonic","AppVersion":"buyonic - 1.3.14117","PreferredICPriority":"32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000,32000","ExternalAccountKey":"5200714","ChosenICLocation":"Transport Drive I.C.","ImpersonatedBy":"","PreferredIC":"Atlanta Stockbridge I.C.,Birmingham I.C.,Blue Mound I.C.,Chicago I.C.,Clearwater I.C.,Cleveland I.C.,Columbus I.C.,Delanco I.C.,Denver I.C.,Detroit I.C.,Fontana I.C.,Foster Road I.C.,Fremont I.C.,Ft. Worth I.C,Highland I.C.,Houston Kuykendahl I.C.,Kansas City I.C.,Memphis I.C.,Mobile I.C.,Montclair I.C.,Nashville I.C.,Orlando I.C.,Philadelphia I.C,Phoenix I.C.,Pittsburgh I.C.,Redbird I.C.,Shadeland I.C.,Transport Drive I.C.,West Palm Beach I.C.,Wyoming I.C.","EventValue":"undefined","EmployeeId":"00000","BidAmount":"00000","BidMethod":"Proxy","SaleDate":"09-19-2018","PageName":"Preview 9/19/2018","Platform":"Android","IDNumber":",,,,,,,,,,,,,,,,,,,,,,,,,,,,,","Email":"N/A","Auction":"ADESA PA","Action":"Add/Update Proxy Bid","House":"ADESA","Label":"bid","Page":"file:///android_asset/www/index.html#","Size":"MEDIUM","Vin":"1N4AL3AP8FC182178"}_

**Comment by dehru** [comment]
Chrome: 81
Application Insights JavaScript SDK - Web, 2.5.2

I'm seeing duplication too.  Though my use case is slightly different.  I send an event and a metric right before a rewrite of the url.  ( window.location.href="new url" ).  Those 2 events do get sent via http...that send is likely triggered via the onBeforeUnload event handler in app insights.  That http event is cancelled by the browser because of the url rewrite.  But those events do reach app insights and get logged.  However, the 2 events also get stored in local session storage.  Once the user comes back to the original url, app insights sees the 2 events in local storage and sends them again.

Here is the network traffic showing the 2 events sent just before window.location.href change:
<img width="474" alt="resent-request-on-user-return" src="https://user-images.githubusercontent.com/599418/80758918-aa798c80-8af3-11ea-8b2e-edded50af17f.png">


Here's the network traffic when the user returns to the app, and it shows the 2 events getting sent again:
<img width="920" alt="cancelled-request-before-navigation" src="https://user-images.githubusercontent.com/599418/80758828-7ef6a200-8af3-11ea-90bf-9f53eb14a733.png">


I can fix this behavior by setting "isStorageUserDisabled: true" in the config.  But I wanted to report this issue.  And also wondered if there are other config settings that would be less drastic than completely disabling storage.  I tried "enableSessionStorageBuffer: false" but that didn't seem to change the duplication.  And enabling the beaconApi also does not change this behavior.
