### ISSUE TITLE
Save events tracked in beforeUnload

### ISSUE THREAD

**Issue by ptrstpp950** [Microsoft/ApplicationInsights-JS#445]
I'm trying to save custom metric - how long user was on mu page - using Application Insights. I wrote following code (it is a part):
```
 var start = new Date();
            
var recordMetrics = function () {
    var end = new Date();
    var timeSpentTotal = (end.getTime() - start.getTime()) / 1000;
    if (window.appInsights) {
        window.appInsights.trackMetric("timeSpentTotal", timeSpentTotal);
        window.appInsights.flush();
        console.log("Sent data with timeSpent");
    }
}
window.addEventListener("beforeunload",
    function (e) {
        recordMetrics();
    });
```
But every request after the `flush` function is canceled. I'm almost sure that this is because App Insights create asynchronous AJAX request. Can I somehow change this to synchronous?

**Comment by OsvaldoRosado** [comment]
`beforeunload` is a tricky event to work with, mainly because of the asynchronous problem you've identified. We have some code to try to send events for you during beforeunload, as a best effort. (See https://github.com/Microsoft/ApplicationInsights-JS/blob/cac7b363a7f59147adff510f698bc3f4943f2ab0/JavaScript/JavaScriptSDK/Initialization.ts#L120 for reference)

Using flush like this should be synchronous however. Are you finding that is not the case? Perhaps try `appInsights.context._sender.triggerSend(false);` instead.

**Comment by ptrstpp950** [comment]
Can I create a pull request with a boolean parameter in `flush` method?
Using "private" method is like a naughty hack

**Comment by OsvaldoRosado** [comment]
Can you first verify that flush is sending asynchronously? The documentation for that method says it should be synchronous. The workaround I suggested is of course not a permanent fix if this is the case, but something to unblock between SDK releases

**Comment by KamilSzostak** [comment]
Adding a bool parameter to `flush` method to force it to be synchronous is a good idea. Please feel free to send a PR. 

By default, the SDK will not block the user from navigating to a new page (e.g. by calling sync flush) as this may impact the navigation experience. But of course, there is nothing stopping the developer to block the navigation. Please keep in mind that this is not guaranteed to work because the browser may close any pending requests and terminate any script execution. 

Another option is to use a [Beacon API](https://www.w3.org/TR/beacon/), which the SDK will support in v1.0.9 (#394). We are planning to release this version on May 8th. You can enable it using the `isBeaconApiDisabled` (see [config](https://github.com/Microsoft/ApplicationInsights-JS/blob/e6cc95238374270e43534b4cbeb8fa659656c777/API-reference.md#config)). 

This is an experimental feature. It would help us a lot if you could share your feedback (negative and positive) if you decide to use it. Thank you!
