### ISSUE TITLE
Consider changing cookie names

### ISSUE THREAD

**Issue by blowdart** [microsoft/ApplicationInsights-JS#494]
The AI cookies are named ai_session and ai_user, and have caused problems with Qualsys WAS Scan. 

The scanning tool assumes that because they are called session and user they are, in fact, application session cookies and application authentication cookies, and thus flags them as insecure (because they're not HTTPS only and are accessible through javascript).

Renaming the cookies to something less worrisome, or allowing a developer to change the cookie names, would stop false positives for this and other tools.

**Comment by SergeyKanzhelev** [comment]
do you have suggestion for alternative names? We need to keep them human friendly and not look proprietary and cryptic. And they ARE user and session for the application.

**Comment by blowdart** [comment]
ai_id, ai_activity?

**Comment by SergeyKanzhelev** [comment]
both of these names do not explain the content of a cookie as it is not clear that id is an anonymous user id and activity is another name for session. Maybe an option is to go totally cryptic than. GA for instance goes all the way to super cryptic using something like `__utmz`.

**Comment by blowdart** [comment]
Cryptic is fine by me, it avoids all those false triggers that make assumptions :)

**Comment by OsvaldoRosado** [comment]
Is there a clear way to change this while not breaking compatibility with server-side SDKs that read the cookie value for correlation? It seems to me like any change here will need a long migration period.

**Comment by SergeyKanzhelev** [comment]
I'd say we need more feedback on this. As @OsvaldoRosado we need more customer's confirmation to justify the investment.

**Comment by KamilSzostak** [comment]
@blowdart what do you mean by "flags them as insecure"? Could you provide more details? 

JS SDK will use secure cookies for pages served using https, see #379. 
AI_user cookie isn't marked as HTTP only (it's similar to what GA and FB scripts are doing) and it can't be because we need to access it in JavaScript. 
![image](https://user-images.githubusercontent.com/12164228/29041837-3bee0da0-7b69-11e7-9af0-fd0a5df9f2bb.png)

Changing the cookie name doesn't make it any more secure :) Instead I would try to understand why the tool is saying that they are insecure. Changing the name will only mask the issue - in this case, it might be sending cookies using http instead of https, or WAS Scan over triggering.

**Comment by blowdart** [comment]
The names you choose confuse security scanners into thinking they're server side auth and session cookies.

As you set them in javascript they are not HTTP only, which is what triggers the warnings.

As you can't make them HTTP only the only way to reduce false positives is change the name.

**Comment by MSNev** [comment]
As there has been no additional comments on this for a while, I'm closing the issue. If still required please feel free to comment and re-open.
