### ISSUE TITLE
One of telemetry initializers failed, telemetry item will not be sent

### ISSUE THREAD

**Issue by gatimus** [Microsoft/ApplicationInsights-JS#534]
When an `XMLHttpRequest` is made with `undefined` url, it causes warning:

> AI: TelemetryInitializerFailed message:"One of telemetry initializers failed, telemetry item will not be sent: TypeError" props:"{exception:[object Error]{ stack: 'TypeError: Cannot read property 'indexOf' of null\n at c (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:3:1690)

[Here](https://plnkr.co/edit/HUXeEVozVIRc2aVfHvZE?p=preview) is a plunker to demonstrate. Replace instrumentationKey in index.html

**Comment by jpiyali** [comment]
This will be updated in beta of version 2 of SDK (pushing fix today) in 2.0.2-beta

**Comment by jpiyali** [comment]
This fix in latest release of the beta SDK: 
NPM: https://www.npmjs.com/package/@microsoft/applicationinsights-web
Beta sdk readme: https://github.com/Microsoft/ApplicationInsights-JS/blob/master/AISKU/README.md

**Comment by ImDmj** [comment]
@jpiyali 
Hey
I still this error when i try to access user.id or user.authID within envelope.ext
i am trying to set user.id with authID, but i am not able to. 
I am running on @microsoft/applicationinsights-web: 2.0.0-rc4

**Comment by ketaanhshah** [comment]
Hi All,
One of our application uses Application Insights and we observed following error being reported in the Application Insights, can someone help me understand how we can fix it:

AI: TelemetryInitializerFailed message:"One of telemetry initializers failed, telemetry item will not be sent: TypeError" props:"{exception:[object Error]{ stack: 'TypeError: Cannot read property 'correlationKey' of undefined\n at https://quote.threeinsurance.com/quote/generating:47:42\n at n._track (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:71156)\n at n.track (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:69930)\n at n.trackDependencyData (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:85929)\n at n.onAjaxComplete (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:46357)\n at XMLHttpRequest. (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:45057)', message: 'Cannot read property 'correlationKey' of undefined', name: 'TypeError'}"

Is this because of the AI Version used? seems like it is ai.0.js .. not sure what it means any help please?

Thanks,
