### ISSUE TITLE
trackPageView reusing landing page Page view duration instead of the current page

### ISSUE THREAD

**Issue by chazguerrero** [Microsoft/ApplicationInsights-JS#570]
We are trying to get data out of AI, however in the current state we get the same time in the page view duration and never resets.

Do you guys know how we can fix this?

**Comment by jpiyali** [comment]
What kind of application is being instrumented? Can you share some details please?

**Comment by chazguerrero** [comment]
We are running an angular 2+ SPA. Here is a snippet of the code we use to specify a page view change. So what happens is first page gets time 0 - 2 sec. when we switch to the next page instead of going from 2- 7 sec (5 seconds) it says we were on the second page for 0 -7  (7 seconds)

```javascript

  private _setupLocationAnalytics(): void {
    let firstRouteChange = true;
    this._router.events.subscribe(async event => {
      if (event instanceof NavigationEnd) {
        if (firstRouteChange) {
          firstRouteChange = false;
        } else {
          // We want to defer to the back of the event loop for all pageviews so that we aren't setting the page
          // to the "next" page before we log click events from the "prior" page that may have caused the page change action.
          await AsyncUtils.nextTick();
        }
        if (!RouterUtils.getCurrentRouteData(this._activatedRoute).delayedPageView) {
          this.logAppInsightsPageView();
        }
      }
    });
  }

  public logAppInsightsPageView(customData: IDictionary<string|number> = null): void {
    if (cmp.isDefinedAndNotNull(this.appInsights)) {
      customData = this._appendRouteData(customData);
      customData.leadSubmissionId = this._typeStoreService.Lead().getFromStore().leadSubmissionId;
      this.appInsights.trackPageView(null, null, customData);
    }
  }

```

**Comment by jpiyali** [comment]
@chazguerrero - my sincere apologies for the delay in replying to the thread. Angular spa applications have a single page model. Page performance data that is collected by application insights uses data from the browser window object (https://www.w3.org/TR/navigation-timing/#processing-model) 

Since this does not update with page navigation in SPA, hence you are seeing the same page view duration in all cases. You'll need to capture duration through [startTrackpage()](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#starttrackpage), [stoptrackPage()](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#stoptrackpage)

**Comment by chazguerrero** [comment]
@jpiyali Thank you will we give it a try!

**Comment by jpiyali** [comment]
@chazguerrero - please let us know if you need further input on this apis.
