### ISSUE TITLE
Improve transmission reliability

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-JS#69]
See https://w3c.github.io/beacon/

**Comment by MaxShehovtsov** [comment]
This is an interesting API however it seems to have poor browser support. We could try using it for FF and Chrome only.

**Comment by AlexBulankou** [comment]
Changing the title of this issue, so we track the generic way to address this problem - today we are losing about 10% of all telemetry documents that customers are sending, mostly due to navigating away. One way to address it is to store unsent telemetry items in session or local storage and attempt resending on page transition.

**Comment by AlexBulankou** [comment]
We discussed that this item should include supporting
persisting in session or local storage 
P1. retrying in case user navigates away before sending and comes back
P2. retrying in case of error from DC endpoint
P3. retrying in case of lost connection

**Comment by oising** [comment]
Beacon definitely looks promising. 

http://status.modern.ie/beacon

**Comment by kamilszostak** [comment]
Thanks @oising for mentioning the Beacon API. We will consider using it, but it may not be possible because Beacon API does not provide a response callback.

**Comment by alippai** [comment]
This shouldn't be closed. Beacon API is living standard and it was designed for this behavior.

**Comment by SergeyKanzhelev** [comment]
@AlexBulankou repurposed this issue for another investigation. @AlexBulankou , @kamilszostak - should we open another one specifically for beacon API?
