### ISSUE TITLE
Include prefix.js into Microsoft.ApplicationInsights.JavaScript

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-JS#75]
It is a good idea to include the snippet as a script into NuGet package as discussed here:

https://github.com/Microsoft/ApplicationInsights-aspnet5/issues/120#issuecomment-156197242

**Comment by RehanSaeed** [comment]
The snippet.html file does not seem to be checked-in, although it is referred to in the [NuGet.JavaScript.csproj](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/NuGet.JavaScript/NuGet.JavaScript.csproj) project as `..\JavaScriptSDK\min\snippet_vsix.html`. The same can be said for the ai.js and ai.min.js files. Am I missing something?

**Comment by SergeyKanzhelev** [comment]
See https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/JavaScriptSDK/min/snippet.ps1 referred into JavaScriptSDK project file

**Comment by RehanSaeed** [comment]
I see. I'm not much of an expert in PowerShell. I could copy the snippet.ps1 file and create one that generates a .js file but then most of the script will be the same and I'm not sure how you can do code reuse in PowerShell. Am I on the right track?

**Comment by MaxShehovtsov** [comment]
Can you describe again why do we need this change? (I tried to follow Microsoft/ApplicationInsights-aspnet5#120 (comment) but it didn't really made sense to me)

**Comment by RehanSaeed** [comment]
I want to add application insights as a separate JavaScript file, rather than inline script. This is to enable Content Security Policy (CSP) HTTP header compatibility (Inline scripts are not allowed without adding a hash or nonce attribute with specially computed values) for better security. According to the link posted by @SergeyKanzhelev, this also helped the Glimpse team achieve better performance. 

To achieve this I want to use the gulp-replace plugin to insert the instrumentation key into the application insights JavaScript file in my ASP.NET 5 project template. I could grab a copy of the file but I would have to update it myself when Microsoft changes it. It would be nice if the file came straight from a NuGet package which can be updated.

It would be even better if Microsoft released a Bower package for application insights explicitly for this purpose. @SergeyKanzhelev @MaxShehovtsov, what is Microsoft's appetite for this?

**Comment by MaxShehovtsov** [comment]
So once again, why prefix.html from nuget doesn't work?

**Comment by RehanSaeed** [comment]
I need a separate .js file. I could use the .html file but then I would have to strip out the <script> tags using yet another Gulp plugin.

**Comment by MaxShehovtsov** [comment]
String out what? :)

**Comment by SergeyKanzhelev** [comment]
```<script>``` tag

**Comment by RehanSaeed** [comment]
I have updated the [ASP.NET MVC Boilerplate](https://visualstudiogallery.msdn.microsoft.com/6cf50a48-fc1e-4eaf-9e82-0b2a6705ca7d), please see [this](https://github.com/Microsoft/ApplicationInsights-aspnet5/issues/120#issuecomment-155918711) issue for more information.

**Comment by RehanSaeed** [comment]
I have spotted an applicationinsights-js bower package with the snippet.js file in it. I can now use that file.
