### ISSUE TITLE
Support ajax monitoring

### ISSUE THREAD

**Issue by MaxShehovtsov** [Microsoft/ApplicationInsights-JS#84]
**Ajax calls** are instrumented by overriding prototype.open and prototype.send functions, and onreadystatechange event handler of XMLHttpRequest. 

This is an entrypoint for ajax auto collection: https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/JavaScriptSDK/ajax/ajax.ts

Below is the ajax monitoring sequence chart:

* **XHR** – an instance of XMLHttpRequest
* **User-defined** callbacks – while appInsights subscribes (‘attaches’) to XMLHttpRequest.onreadystatechange event there might be other event handlers before or after (if user subscribed before or after initialization of appInsights object).
* **AjaxMonitor** and **AjaxRecord** are the new appInsights entities added for supporting ajax monitoring.
* **AppInsights** is the object exposing our public API (trackXXX methods) and initializing javascript monitoring.

![](https://cloud.githubusercontent.com/assets/10049593/11410408/fe9c0b0e-937b-11e5-9047-19435bfdfa8a.png)

**Comment by SergeyKanzhelev** [comment]
Questions: 
- How monitoring will behave if `send` will be sent again before the callback or result returned?
- Is it a valid scenario to do multiple `send` for one `open`?
- Will we detect long-poll ajax calls and adjust their processing so they do not make average ajax execution time enormously big?
- Do we instrument `abort` method?
- is `Callbacks` only stored in `XHR` object itself? If not - will it keep it from being garbage collected as it keeps delegates on it?
- Will the `ajaxRecord` stay alive after `trackAjax` call? Will Callbacks unsubscribe of `onreadystatechange` after that?
- Do we plan to stop and send in-flight ajax calls on page `onbeforeunload` callback?

As a side note I'd advice to set a lock when you call `original Open` and `original Send` so that "originl" callback wouldn't call you back and enter recursion in case when customer application has some logic that also does override of `XHR` and do not expect somebody in the middle to change callbacks.

**Comment by MaxShehovtsov** [comment]
Thank you for the feedback:

- 2nd should fail (and does so in chrome), however we shouldn't execute send handler 2nd time. I'm adding validations for this.
- long ajax - I think they will be there, spoiling averages, and it's by design
- We do instrument abort however we currently don't send any data about abortion status. So depending on timing when abort was called - if request succeeds it'll be treated as any other ajax call. It makes sense to send the custom property with abortion status though.
- by callbacks i mean 2 different things 1) the xhr instance owns the onreadystatechange callback, it lives on xhr and dies with it. 2) there is an event listenerer for "readystatechange" event - this one lives on ajaxMonitor instance, however it gets unsubscribed once xhr is complete. Unless the number of xhr instances that are not completed (aborted or finished) grows we should be ok. Otherwise we'll not be major contributors to the memory growth.
- ajaxRecord dies with xhr
- onbeforeunload proved unusable for events sending, so all open ajaxes will be lost (similarly to other batched telemetry unless batch timeout and/or batch size is overriden)

**Comment by bengreenier** [comment]
i noticed there's no milestone associated with this issue - any idea when this feature will be officially supported/fully documented?

**Comment by MaxShehovtsov** [comment]
Hopefully within next couple weeks

**Comment by bengreenier** [comment]
bump - any updates here?

**Comment by MaxShehovtsov** [comment]
@bengreenier It's actually done - https://azure.microsoft.com/en-us/blog/ajax-collection-in-application-insights/
P.s. I thought I closed this issue - my bad it's left open, sorry.
