### ISSUE TITLE
Correlation not working

### ISSUE THREAD

**Issue by LeopoldLerch** [microsoft/ApplicationInsights-JS#863]
Hi, 
I am using 2.0.0-rc4

I am sending Ajax-requests to my web service. However, I am not able to bring them together. I guess it is because the "request-id" header always consists of just "f1+QH".

I debugged it down to this line in AjaxMonitor.prototype.createFetchRecord

`        if (this._context && this._context.telemetryTrace && this._context.telemetryTrace.traceID) {
            // this format corresponds with activity logic on server-side and is required for the correct correlation
            id = "|" + this._context.telemetryTrace.traceID + "." + Util_Util.newId();
        }
        else {
            id = Util_Util.newId();
        }`

_context is always empty, so it always just generates a plain ID and then is not able to connect it to the operation.

this seems to be due this line in AjaxMonitor.prototype.initialize:

`            if (extensions.length > 0 && extensions) {
                var propExt = extensions[PropertiesPluginIdentifier];
                if (propExt) {
                    this._context = propExt.context; // we could move IPropertiesPlugin to common as well
                }
            }`

Altough there is an Key for an PropertiesPlugin in extensions, it is named "PropertiesPlugin", not "AppInsightsPropertiesPlugin", what is the value of the variable (altough the Object referenced has an "Identifier" with that value").

However, due to that "_context" is null and therefore the requestId cannot be generated to correlate the request with the server-side metrics.

Pls have a look into that

**Comment by jdudleyie** [comment]
Hi,

I was coming here to report an issue - it looks like it might be the same issue as this one. If not please let me know and I can move this into a new Issue.

I have an Angular app sending ajax requests to my .NET Core API. Both my Angular App and my .NET Core API are running in different containers/pods in Kubernetes.

I have added my Application Insights Instrumentation Key to both of them, and added the relevant code.

I can see both on my Application Map in the Azure Portal, but although my client calls my API, the calls do not link up - i.e. it shows the 1) client ajax call target and the 2) API as two separate nodes - even though they are the same thing.

As the target of my client ajax calls is "api.todocalendar.app", and my API was labelled as "todo-calendar-api" - in an effort to link them I tried setting the "telemetry.Context.Cloud.RoleName" to "api.todocalendar.app" - but it still showed them as separate nodes (I have since removed this change.

I also tried adding "Microsoft Application Insights for Kubernetes" - I see the extra telemetry fields in my Azure Analytics, but I still have the same issue.

Please see the attached photo as illustration. In the photo I wanted the nodes "todo-calendar-api" (bottom) and "api.todocalendar.app" (top right) to be merged, with client "app.todocalendar.app" calling the merged node.

![Screenshot from 2019-05-09 13-19-35](https://user-images.githubusercontent.com/3493601/57453304-f5a0ec80-725d-11e9-95a2-a707389a4ed5.png) 

Thanks for your help.

**Comment by LeopoldLerch** [comment]
well, i don´t think it is the same issue. 

And in my opinion, AI is totally right here, they are 2 different nodes. One is the client as a browser, and the other one is a server. The flow can be shown in the same session, but they are different nodes.

However, if you insist on acting the client the same way like the server, you might be able to customize the tags of the events the client sends back

![image](https://user-images.githubusercontent.com/28888039/57454107-5f25f880-7268-11e9-9ea6-d68d29dc8b89.png)


If you adapt these to the values the server sends, then AI should merge them (however, you might be careful then with Instances, IP´s .....)

**Comment by LeopoldLerch** [comment]
Back to the topic:

I managed to get it working with that workaround:

`appInsights.loadAppInsights();
appInsights.trackPageView();

const core = appInsights.core as any;

const extensions = core._extensions as [];

const ajaxMonitor = extensions.find((e: any) => e.identifier === "AjaxDependencyPlugin") as any;
const propertiesplugin = extensions.find((e: any) => e.identifier === "AppInsightsPropertiesPlugin") as any;

if (ajaxMonitor && propertiesplugin) {
    ajaxMonitor._context = propertiesplugin.context;
}
`

now the context is there and the parent-relationships can be transfered successfully, via the now correct "Request-ID"-header of eg: "|SMI1u.BTAxg"

Could someone have a look at this?

**Comment by jdudleyie** [comment]
Hi Leopold,

Thanks for your reply - sorry I didn't mean to contribute to this thread if my issue was different - can I just ask - you said that "One is the client as a browser, and the other one is a server" - I am not sure if I explained myself well enough. I have updated the image to show the two nodes which I would like to be merged - it's not the client I want to merge but the "server" it's calling with the actual API server. Does that make sense? If you still think what I am asking is incorrect please let me know. Thanks.

![Screenshot from 2019-05-09 13-19-35](https://user-images.githubusercontent.com/3493601/57469898-9522a700-727f-11e9-85e9-64238bcc6b43.png)

**Comment by LeopoldLerch** [comment]
Well, then it might be the same issue. Obviously it is already fixed and we should see it in the next release. However, you can also try my workaround mentioned above to see if it helps

**Comment by markwolff** [comment]
Closing this as the fix has dropped in `2.0.0-rc5`
