### ISSUE TITLE
PageView is not parent of Ajax and Fetch Calls

### ISSUE THREAD

**Issue by LeopoldLerch** [microsoft/ApplicationInsights-JS#868]
For some reason, the PageView Event is logged aside all the AJAX-Fetch Calls. Shouldn´t it be the parent of them ?

![image](https://user-images.githubusercontent.com/28888039/57528683-3fa7d200-7333-11e9-88cc-e80d585ef264.png)

**Comment by markwolff** [comment]
Can you post a sample operationId, parentId, Id set for these? Also, if there is an issue with this, it might be related to #863, which was fixed in rc5. You can grab rc5 from npm now and see if the behavior changes.
Also see https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation#example

**Comment by markwolff** [comment]
Closing as it seems this was fixed with the release of rc5
