### ISSUE TITLE
CorrelationHeaders are attached even if disableTelemetry is true

### ISSUE THREAD

**Issue by LeopoldLerch** [microsoft/ApplicationInsights-JS#879]
As the title states.

Even if disableTelemetry in the config is set to false, altough nothing is tracked and sent, the correlation-headers are still attached to the requests (fetch/ajax).

**Comment by LeopoldLerch** [comment]
I mean, I can change that in Utils.ts. and make a new PR.

But I guess there is a more "lower" Level place to stop the interception of Ajax/fetch calls at all when that config value is set. Would be more suitable than just the method for the correlation-headers itself.

**Comment by markwolff** [comment]
I would say this is by design. The intent of the disableTelemetry option is to only disable sending telemetry to Azure. All collection still takes place and could be logged to console instead, for example. 

There has been discussion in other SDKs to expose a flag to completely disable all collection and side effects, but no implementation for this has been worked on yet, https://github.com/microsoft/ApplicationInsights-dotnet-server/issues/590. In the meantime, to disable the correlation headers you can use `disableCorrelationHeaders: true`.
