### ISSUE TITLE
New Snippet Setup pollutes the global namespace (window)

### ISSUE THREAD

**Issue by PeterOrneholm** [microsoft/ApplicationInsights-JS#974]
Using the new [Snippet Setup](https://github.com/microsoft/ApplicationInsights-JS#snippet-setup-ignore-if-using-npm-setup) introduces 5 global variables (on the window object). I can see the following being added to window.

- `aisdk`
- `ainame`
- `appInsightsSDK`
- `appInsights`
- `sdkInstance`

Is this really necessary? Is there any usecase for when I should use / change these variables? I'd like a minimal global footprint (`appInsights`) and scope the rest to a local function. IF, they need to be global for some reason, a consistent prefix should be in place IMHO; `sdkInstance` feels very generic.

**Comment by MSNev** [comment]
An update snippet which address this issue has been checked in with #1258 
This also updated the Readme, so it's now available on the readme page, will close this issue once we publish a full release so that the snippet.js and snippet.min.js are included in the NPM packages.
The snippet change is a lot larger because it's closing a gap that existed by sending an exception event to the server when it detects that the main SDK script could not be downloaded from the CDN, it also has some additional snippet only configuration options.

**Comment by MSNev** [comment]
Included in v 2.5.5 which is now fully deployed
